'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Building2, CalendarDays, Clock, Filter, Key, Mail, Pencil, Phone, Plus, Power, Search, Shield, Trash2, UserCheck, Users, X } from 'lucide-react';
import CrmHeader from '../components/CrmHeader';
import ConfirmDialog from '../components/ConfirmDialog';
import { useSidebar } from '../sidebar-context';
import type { CrmRole, EmploymentType, StaffFilters, StaffFormData, StaffRecord, StaffStatus } from '../lib/types';
import { createBlankStaff, createStaff, deleteStaff, getAllModuleAccess, getNextStaffCode, getStaff, getStaffLastLogin, resetStaffPassword, setStaffActive, updateStaff } from './staff-data';
import ManageAccessModal from './ManageAccessModal';
import { useCrmProfile } from '../lib/useCrmProfile';
import { WORKSPACE_MODULES } from '../../../lib/modulePermissions';
import { CRM_SECTIONS, isCrmAdminRole } from '../../../lib/crmSectionPermissions';

const DEPARTMENTS = ['Operations', 'Sales', 'Client Servicing', 'Production', 'Accounts', 'Marketing', 'IT', 'Management'];
const EMPLOYMENT: EmploymentType[] = ['Full Time', 'Part Time', 'Contract', 'Intern'];
const STATUSES: StaffStatus[] = ['Active', 'On Leave', 'Inactive'];
const STATUS_STYLE: Record<StaffStatus, string> = { Active: 'bg-emerald-50 text-emerald-700', 'On Leave': 'bg-amber-50 text-amber-700', Inactive: 'bg-gray-100 text-gray-600' };
const ROLES: { value: CrmRole; label: string }[] = [
  { value: 'staff', label: 'Staff' }, { value: 'sales', label: 'Sales Executive' }, { value: 'manager', label: 'Manager' },
  { value: 'vendor', label: 'Vendor Coordinator' }, { value: 'accountant', label: 'Accountant' },
  { value: 'admin', label: 'Admin' }, { value: 'super_admin', label: 'Super Admin' },
];

function ResetPasswordModal({ staff, onClose }: { staff: StaffRecord; onClose: () => void }) {
  const [password, setPassword] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [done, setDone] = useState(false);
  const submit = async () => { if (password.length < 8) { setError('Password must be at least 8 characters.'); return; } setSaving(true); setError(''); try { await resetStaffPassword(staff.id, password); setDone(true); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not reset password.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-[110] flex items-center justify-center bg-gray-950/60 p-5 backdrop-blur-sm" onMouseDown={event => event.target === event.currentTarget && onClose()}><div className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl">
    <h2 className="text-lg font-black text-gray-950">Reset password</h2>
    {done ? <><p className="mt-3 text-sm text-gray-600">Password updated for <b>{staff.full_name}</b>. Share it with them securely.</p><button onClick={onClose} className="mt-5 w-full rounded-xl bg-red-600 px-4 py-2.5 text-xs font-bold text-white">Done</button></> : <>
      <p className="mt-1 text-xs text-gray-400">New login password for {staff.full_name} ({staff.crm_id || staff.email}).</p>
      <input type="text" value={password} onChange={e => setPassword(e.target.value)} placeholder="New password" className="mt-4 w-full rounded-xl border border-gray-200 px-3.5 py-2.5 text-sm outline-none focus:border-red-400" />
      {error && <p className="mt-2 text-xs font-semibold text-red-600">{error}</p>}
      <div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-xs font-bold">Cancel</button><button onClick={submit} disabled={saving} className="rounded-xl bg-red-600 px-5 py-2.5 text-xs font-bold text-white disabled:opacity-50">{saving ? 'Saving...' : 'Reset password'}</button></div>
    </>}
  </div></div>;
}

function Field({ label, required, children, wide }: { label: string; required?: boolean; children: React.ReactNode; wide?: boolean }) {
  return <label className={`agreement-field ${wide ? 'sm:col-span-2' : ''}`}><span>{label}{required && <b className="ml-1 text-red-600">*</b>}</span>{children}</label>;
}

function StaffModal({ initial, nextCode, onClose, onSaved }: { initial: StaffRecord | null; nextCode: string; onClose: () => void; onSaved: (record: StaffRecord) => void }) {
  const [data, setData] = useState<StaffFormData>(initial || createBlankStaff(nextCode)); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const text = (key: keyof StaffFormData, value: string) => setData(current => ({ ...current, [key]: value }));
  const submit = async () => {
    if (!data.employee_code.trim() || !data.full_name.trim() || !data.mobile.trim() || !data.job_title.trim() || !data.department.trim() || !data.joining_date || !data.crm_id.trim()) { setError('Employee code, CRM ID, name, mobile, job title, department and joining date are required.'); return; }
    if (!initial && (!data.email.trim() || !data.password || data.password.length < 8)) { setError('A login email and a password of at least 8 characters are required to create this staff member’s CRM login.'); return; }
    setSaving(true); setError(''); try { onSaved(initial ? await updateStaff(initial.id, data) : await createStaff(data)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save staff member.'); } finally { setSaving(false); }
  };
  return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-gray-950/60 p-0 backdrop-blur-sm sm:items-center sm:p-5" onMouseDown={event => event.target === event.currentTarget && onClose()}><div className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl"><div className="sticky top-0 z-10 flex items-start justify-between border-b border-gray-100 bg-white px-5 py-4 sm:px-7"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-red-600">Team directory</p><h2 className="mt-1 text-xl font-black text-gray-950">{initial ? 'Edit staff profile' : 'Add staff member'}</h2><p className="mt-1 text-xs text-gray-400">Employment, shift, emergency and CRM login information in one secure profile.</p></div><button onClick={onClose} className="rounded-xl p-2 text-gray-400 hover:bg-gray-100"><X size={19} /></button></div><div className="grid gap-5 p-5 sm:grid-cols-2 sm:p-7">
    <Field label="Employee code" required><input value={data.employee_code} onChange={event => text('employee_code', event.target.value.toUpperCase())} /></Field><Field label="Full name" required><input value={data.full_name} onChange={event => text('full_name', event.target.value)} /></Field>
    <Field label="Mobile" required><input type="tel" value={data.mobile} onChange={event => text('mobile', event.target.value)} /></Field><Field label="Email" required={!initial}><input type="email" value={data.email} onChange={event => text('email', event.target.value)} disabled={!!initial} className={initial ? 'bg-gray-50 text-gray-500' : ''} /></Field>
    <Field label="Job title" required><input value={data.job_title} onChange={event => text('job_title', event.target.value)} placeholder="e.g. Event Operations Manager" /></Field><Field label="Department" required><select value={data.department} onChange={event => text('department', event.target.value)}>{DEPARTMENTS.map(item => <option key={item}>{item}</option>)}</select></Field>
    <Field label="Employment type"><select value={data.employment_type} onChange={event => text('employment_type', event.target.value)}>{EMPLOYMENT.map(item => <option key={item}>{item}</option>)}</select></Field><Field label="Status"><select value={data.status} onChange={event => text('status', event.target.value)}>{STATUSES.map(item => <option key={item}>{item}</option>)}</select></Field>
    <Field label="Joining date" required><input type="date" value={data.joining_date} onChange={event => text('joining_date', event.target.value)} /></Field><Field label="Date of birth"><input type="date" value={data.date_of_birth} onChange={event => text('date_of_birth', event.target.value)} /></Field>
    <Field label="Shift start"><input type="time" value={data.shift_start} onChange={event => text('shift_start', event.target.value)} /></Field><Field label="Shift end"><input type="time" value={data.shift_end} onChange={event => text('shift_end', event.target.value)} /></Field>
    <Field label="Work location" wide><input value={data.work_location} onChange={event => text('work_location', event.target.value)} /></Field><Field label="Residential address" wide><textarea rows={2} value={data.address} onChange={event => text('address', event.target.value)} /></Field>
    <Field label="Emergency contact name"><input value={data.emergency_contact_name} onChange={event => text('emergency_contact_name', event.target.value)} /></Field><Field label="Emergency contact mobile"><input value={data.emergency_contact_mobile} onChange={event => text('emergency_contact_mobile', event.target.value)} /></Field>
    <Field label="Internal notes" wide><textarea rows={3} value={data.notes} onChange={event => text('notes', event.target.value)} /></Field>
    <div className="sm:col-span-2 mt-1 rounded-2xl border border-red-100 bg-red-50/40 p-4"><p className="text-[10px] font-black uppercase tracking-[.2em] text-red-600">CRM login</p><div className="mt-3 grid gap-4 sm:grid-cols-3">
      <Field label="Staff CRM ID" required><input value={data.crm_id} onChange={event => text('crm_id', event.target.value)} placeholder="Unique username or email" /></Field>
      <Field label="Role" required><select value={data.role} onChange={event => text('role', event.target.value)}>{ROLES.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></Field>
      {!initial && <Field label="Password" required><input type="text" value={data.password || ''} onChange={event => text('password', event.target.value)} placeholder="Min. 8 characters" /></Field>}
    </div>{initial && <p className="mt-2 text-[11px] text-gray-400">Use the key icon on the staff list to reset this person&apos;s password.</p>}</div>
  </div>{error && <div className="mx-5 mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700 sm:mx-7">{error}</div>}<div className="sticky bottom-0 flex justify-end gap-2 border-t border-gray-100 bg-gray-50 px-5 py-4 sm:px-7"><button onClick={onClose} className="rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-xs font-bold">Cancel</button><button onClick={submit} disabled={saving} className="rounded-xl bg-red-600 px-5 py-2.5 text-xs font-bold text-white disabled:opacity-50">{saving ? 'Saving...' : initial ? 'Save changes' : 'Add staff member'}</button></div></div></div>;
}

export default function StaffPage() {
  const { open } = useSidebar(); const { profile } = useCrmProfile(); const isOwnerAdmin = isCrmAdminRole(profile?.role); const [staff, setStaff] = useState<StaffRecord[]>([]); const [loading, setLoading] = useState(true); const [filtersOpen, setFiltersOpen] = useState(false); const [filters, setFilters] = useState<StaffFilters>({ search: '', department: '', status: '', employment_type: '' }); const [editing, setEditing] = useState<StaffRecord | null | undefined>(undefined); const [nextCode, setNextCode] = useState('PMB-001'); const [deleteTarget, setDeleteTarget] = useState<StaffRecord | null>(null);
  const [resetTarget, setResetTarget] = useState<StaffRecord | null>(null); const [lastLogin, setLastLogin] = useState<{ id: string; text: string } | null>(null); const [toggling, setToggling] = useState<string | null>(null);
  const [accessTarget, setAccessTarget] = useState<StaffRecord | null>(null);
  const [accessMap, setAccessMap] = useState<Record<string, { role: string; module_access: Record<string, boolean>; crm_section_access: Record<string, boolean> }>>({});
  const load = useCallback(async () => { setLoading(true); try { setStaff(await getStaff(filters)); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { const timer = window.setTimeout(load, 200); return () => clearTimeout(timer); }, [load]);
  useEffect(() => { if(isOwnerAdmin)getAllModuleAccess().then(setAccessMap).catch(() => {}); else setAccessMap({}); }, [staff.length,isOwnerAdmin]);
  const moduleCount = (item: StaffRecord) => {
    if (!item.user_id) return null;
    const entry = accessMap[item.user_id];
    if (!entry) return null;
    if (['admin', 'super_admin'].includes(entry.role)) return 'All';
    if (entry.role === 'manager') return `${Object.values(entry.crm_section_access).filter(Boolean).length}/${CRM_SECTIONS.length} sections`;
    return `${Object.values(entry.module_access).filter(Boolean).length}/${WORKSPACE_MODULES.length}`;
  };
  const openNew = async () => { setNextCode(await getNextStaffCode()); setEditing(null); };
  const stats = useMemo(() => ({ total: staff.length, active: staff.filter(item => item.status === 'Active').length, leave: staff.filter(item => item.status === 'On Leave').length, departments: new Set(staff.map(item => item.department)).size }), [staff]);
  const remove = async () => { if (!deleteTarget) return; await deleteStaff(deleteTarget.id); setDeleteTarget(null); load(); };
  const saved = (record: StaffRecord) => { setEditing(undefined); setStaff(current => editing ? current.map(item => item.id === record.id ? record : item) : [...current, record].sort((a, b) => a.full_name.localeCompare(b.full_name))); };
  const toggleActive = async (item: StaffRecord) => { setToggling(item.id); try { const updated = await setStaffActive(item.id, item.status !== 'Active'); setStaff(current => current.map(s => s.id === item.id ? updated : s)); } catch (cause) { alert(cause instanceof Error ? cause.message : 'Could not update status.'); } finally { setToggling(null); } };
  const viewLastLogin = async (item: StaffRecord) => { if (!item.user_id) { alert('This staff member has no CRM login yet.'); return; } const value = await getStaffLastLogin(item.id); setLastLogin({ id: item.id, text: value ? new Date(value).toLocaleString('en-IN') : 'Never signed in yet' }); };
  return <><CrmHeader title="Staff" subtitle="Team profiles, roles and shift information" onMenuClick={open} actions={isOwnerAdmin?<button onClick={openNew} className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-3.5 py-2 text-xs font-bold text-white"><Plus size={15} /> <span className="hidden sm:inline">Add staff</span></button>:undefined} /><div className="space-y-5 p-4 sm:p-6">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{([["Total staff",stats.total,Users,'bg-gray-950 text-white'],['Active team',stats.active,UserCheck,'bg-white text-gray-950'],['On leave',stats.leave,CalendarDays,'bg-white text-gray-950'],['Departments',stats.departments,Building2,'bg-red-600 text-white']] as Array<[string, string | number, typeof Users, string]>).map(([label,value,Icon,tone]) => <div key={String(label)} className={`rounded-2xl border border-gray-200 p-4 shadow-sm sm:p-5 ${tone}`}><div className="flex justify-between"><p className="text-[10px] font-bold uppercase tracking-widest opacity-60">{String(label)}</p><Icon size={16} className="opacity-60" /></div><p className="mt-4 text-2xl font-black">{String(value)}</p></div>)}</div>
    <div className="flex flex-wrap gap-2"><div className="relative min-w-[220px] flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" /><input value={filters.search} onChange={event => setFilters(current => ({ ...current, search: event.target.value }))} placeholder="Search staff, code, mobile or role..." className="w-full rounded-xl border border-gray-200 bg-white py-2.5 pl-9 pr-4 text-sm outline-none focus:border-red-400" /></div><button onClick={() => setFiltersOpen(value => !value)} className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-xs font-bold"><Filter size={15} /> Filters</button></div>
    {filtersOpen && <div className="grid gap-4 rounded-2xl border border-gray-200 bg-white p-4 sm:grid-cols-3"><label className="agreement-field"><span>Department</span><select value={filters.department} onChange={event => setFilters(current => ({ ...current, department: event.target.value }))}><option value="">All departments</option>{DEPARTMENTS.map(item => <option key={item}>{item}</option>)}</select></label><label className="agreement-field"><span>Status</span><select value={filters.status} onChange={event => setFilters(current => ({ ...current, status: event.target.value }))}><option value="">All statuses</option>{STATUSES.map(item => <option key={item}>{item}</option>)}</select></label><label className="agreement-field"><span>Employment type</span><select value={filters.employment_type} onChange={event => setFilters(current => ({ ...current, employment_type: event.target.value }))}><option value="">All types</option>{EMPLOYMENT.map(item => <option key={item}>{item}</option>)}</select></label></div>}
    <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">{loading ? <div className="flex h-60 items-center justify-center"><span className="h-7 w-7 animate-spin rounded-full border-2 border-gray-200 border-t-red-600" /></div> : !staff.length ? <div className="px-6 py-20 text-center"><Users className="mx-auto text-red-600" size={31} /><p className="mt-4 font-black">No staff members found</p><p className="mt-1 text-sm text-gray-400">No matching staff profiles are available.</p>{isOwnerAdmin&&<button onClick={openNew} className="mt-5 rounded-xl bg-red-600 px-5 py-2.5 text-xs font-bold text-white">Add first staff member</button>}</div> : <><div className="hidden overflow-x-auto md:block"><table className="w-full text-sm"><thead><tr className="border-b bg-gray-50/80">{['Staff member','Role & department','Contact','Employment','Shift','Status','Modules',''].map(item => <th key={item} className="px-4 py-3.5 text-left text-[10px] font-bold uppercase tracking-widest text-gray-400">{item}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{staff.map(item => <tr key={item.id} className="group hover:bg-gray-50"><td className="px-4 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-red-50 text-xs font-black text-red-600">{item.full_name.split(' ').filter(Boolean).map(value => value[0]).slice(0,2).join('')}</span><div><b>{item.full_name}</b><small className="mt-1 block font-mono text-gray-400">{item.employee_code}</small></div></div></td><td className="px-4 py-4"><b className="text-gray-700">{item.job_title}</b><small className="mt-1 block text-gray-400">{item.department}</small></td><td className="px-4 py-4"><span className="flex items-center gap-1.5 text-xs text-gray-600"><Phone size={12} />{item.mobile}</span>{item.email && <span className="mt-1.5 flex items-center gap-1.5 text-xs text-gray-400"><Mail size={12} />{item.email}</span>}</td><td className="px-4 py-4"><b className="text-xs">{item.employment_type}</b><small className="mt-1 block text-gray-400">Joined {new Date(`${item.joining_date}T00:00:00`).toLocaleDateString('en-IN',{month:'short',year:'numeric'})}</small></td><td className="px-4 py-4 text-xs font-semibold">{item.shift_start} – {item.shift_end}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${STATUS_STYLE[item.status]}`}>{item.status}</span></td><td className="px-4 py-4">{isOwnerAdmin?<button onClick={() => setAccessTarget(item)} className="rounded-full border border-gray-200 bg-gray-50 px-2.5 py-1 text-[10px] font-bold text-gray-600 hover:border-red-200 hover:bg-red-50 hover:text-red-600">{moduleCount(item) ?? '—'}</button>:<span className="text-[10px] font-semibold text-gray-400">Owner managed</span>}</td><td className="px-4 py-4">{isOwnerAdmin&&<div className="flex gap-1 opacity-0 group-hover:opacity-100">
                  <button onClick={() => viewLastLogin(item)} title="View last login" className="rounded-lg p-2 text-gray-400 hover:bg-blue-50 hover:text-blue-600"><Clock size={15} /></button>
                  <button onClick={() => setAccessTarget(item)} title="Manage access" className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600"><Shield size={15} /></button>
                  <button onClick={() => setResetTarget(item)} title="Reset password" className="rounded-lg p-2 text-gray-400 hover:bg-purple-50 hover:text-purple-600"><Key size={15} /></button>
                  <button onClick={() => toggleActive(item)} disabled={toggling === item.id} title={item.status === 'Active' ? 'Deactivate account' : 'Activate account'} className="rounded-lg p-2 text-gray-400 hover:bg-emerald-50 hover:text-emerald-600 disabled:opacity-50"><Power size={15} /></button>
                  <button onClick={() => setEditing(item)} className="rounded-lg p-2 text-gray-400 hover:bg-amber-50 hover:text-amber-600"><Pencil size={15} /></button><button onClick={() => setDeleteTarget(item)} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15} /></button></div>}</td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{staff.map(item => <div key={item.id} className="p-4"><div className="flex justify-between gap-3"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-red-50 text-xs font-black text-red-600">{item.full_name?.[0] ?? '?'}</span><div><b>{item.full_name}</b><p className="mt-1 text-xs text-gray-400">{item.job_title} · {item.department}</p></div></div><span className={`h-fit rounded-full px-2 py-1 text-[9px] font-black uppercase ${STATUS_STYLE[item.status]}`}>{item.status}</span></div><div className="mt-3 flex items-center justify-between border-t pt-3 text-xs"><span className="text-gray-500">{item.employee_code} · {item.employment_type}</span>{isOwnerAdmin&&<div className="flex gap-1"><button onClick={() => viewLastLogin(item)} className="p-2 text-blue-600"><Clock size={15} /></button><button onClick={() => setAccessTarget(item)} className="p-2 text-red-600"><Shield size={15} /></button><button onClick={() => setResetTarget(item)} className="p-2 text-purple-600"><Key size={15} /></button><button onClick={() => toggleActive(item)} disabled={toggling === item.id} className="p-2 text-emerald-600 disabled:opacity-50"><Power size={15} /></button><button onClick={() => setEditing(item)} className="p-2 text-amber-600"><Pencil size={15} /></button><button onClick={() => setDeleteTarget(item)} className="p-2 text-red-600"><Trash2 size={15} /></button></div>}</div></div>)}</div></>}</div>
  </div>{editing !== undefined && <StaffModal initial={editing} nextCode={nextCode} onClose={() => setEditing(undefined)} onSaved={saved} />}
  {resetTarget && <ResetPasswordModal staff={resetTarget} onClose={() => setResetTarget(null)} />}
  {accessTarget && <ManageAccessModal staff={accessTarget} onClose={() => setAccessTarget(null)} onSaved={(access) => {
    if (!accessTarget.user_id) return;
    setAccessMap((current) => {
      const existing = current[accessTarget.user_id as string] || { role: accessTarget.role, module_access: {}, crm_section_access: {} };
      const isManagerAccount = existing.role === 'manager';
      return {
        ...current,
        [accessTarget.user_id as string]: {
          ...existing,
          module_access: isManagerAccount ? existing.module_access : access,
          crm_section_access: isManagerAccount ? access : existing.crm_section_access,
        },
      };
    });
  }} />}
  {lastLogin && <div className="fixed inset-0 z-[110] flex items-center justify-center bg-gray-950/60 p-5 backdrop-blur-sm" onMouseDown={event => event.target === event.currentTarget && setLastLogin(null)}><div className="w-full max-w-xs rounded-2xl bg-white p-5 text-center shadow-2xl"><Clock className="mx-auto text-blue-600" size={22} /><p className="mt-3 text-sm font-bold text-gray-900">Last login</p><p className="mt-1 text-xs text-gray-500">{lastLogin.text}</p><button onClick={() => setLastLogin(null)} className="mt-4 w-full rounded-xl bg-gray-100 px-4 py-2 text-xs font-bold text-gray-700">Close</button></div></div>}
  <ConfirmDialog open={!!deleteTarget} title="Delete Staff Member" message={`Delete ${deleteTarget?.full_name}? This also removes their CRM login and attendance history.`} confirmLabel="Delete staff member" onConfirm={remove} onCancel={() => setDeleteTarget(null)} /></>;
}
