'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, Clock3, Eye, Paperclip, Search, X, XCircle } from 'lucide-react';
import CrmHeader from '../components/CrmHeader';
import { useSidebar } from '../sidebar-context';
import type { LeaveRequest, LeaveStatus, LeaveType } from '../lib/types';
import { getLeaveRequests, openLeaveAttachment, reviewLeave } from './leave-data';

const TYPES: LeaveType[]=['Casual Leave','Sick Leave','Paid Leave','Unpaid Leave','Other'];
const STATUS:Record<string,string>={Pending:'bg-amber-50 text-amber-700',Approved:'bg-emerald-50 text-emerald-700',Rejected:'bg-red-50 text-red-700',Cancelled:'bg-gray-100 text-gray-500'};
const nice=(v:string)=>new Date(`${v.slice(0,10)}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
export default function AdminLeavePage(){const{open}=useSidebar();const[rows,setRows]=useState<LeaveRequest[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[search,setSearch]=useState('');const[status,setStatus]=useState('');const[type,setType]=useState('');const[selected,setSelected]=useState<LeaveRequest|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setRows(await getLeaveRequests({status,type,search}));}catch(cause){setError(cause instanceof Error?cause.message:'Unable to load requests.');}finally{setLoading(false);}},[status,type,search]);useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t)},[load]);
 const stats=useMemo(()=>({pending:rows.filter(r=>r.status==='Pending').length,approved:rows.filter(r=>r.status==='Approved').length,rejected:rows.filter(r=>r.status==='Rejected').length,days:rows.filter(r=>r.status==='Approved').reduce((n,r)=>n+r.number_of_days,0)}),[rows]);
 return <><CrmHeader title="Leave Management" subtitle="Review staff requests and keep attendance in sync" onMenuClick={open}/><div className="space-y-5 p-4 sm:p-6"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{([['Pending',stats.pending,Clock3],['Approved',stats.approved,Check],['Rejected',stats.rejected,XCircle],['Approved days',stats.days,CalendarDays]] as const).map(([l,v,I])=><div key={l} className="rounded-2xl border bg-white p-4 shadow-sm sm:p-5"><div className="flex justify-between"><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">{l}</p><I size={16} className="text-red-600"/></div><p className="mt-4 text-2xl font-black">{v}</p></div>)}</div>
 <div className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm md:grid-cols-[1fr_180px_190px]"><label className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search employee or request number" className="w-full rounded-xl border py-2.5 pl-9 pr-3 text-sm outline-none focus:border-red-400"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">All statuses</option>{['Pending','Approved','Rejected','Cancelled'].map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">All leave types</option>{TYPES.map(x=><option key={x}>{x}</option>)}</select></div>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}<div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<div className="flex h-60 items-center justify-center"><span className="h-7 w-7 animate-spin rounded-full border-2 border-gray-200 border-t-red-600"/></div>:!rows.length?<div className="px-6 py-16 text-center"><CalendarDays className="mx-auto text-gray-300"/><p className="mt-3 font-bold">No matching leave requests</p></div>:<><div className="hidden overflow-x-auto lg:block"><table className="w-full text-sm"><thead><tr className="bg-gray-50">{['Request','Employee','Type','Dates','Days','Status',''].map(h=><th key={h} className="px-4 py-3 text-left text-[10px] font-bold uppercase tracking-widest text-gray-400">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="px-4 py-4 font-bold">{r.request_number}<small className="block font-normal text-gray-400">{nice(r.created_at)}</small></td><td className="px-4 py-4"><b>{r.staff?.full_name}</b><small className="block text-gray-400">{r.staff?.employee_code} · {r.staff?.department}</small></td><td className="px-4 py-4">{r.leave_type}</td><td className="px-4 py-4 text-gray-600">{nice(r.from_date)} – {nice(r.to_date)}</td><td className="px-4 py-4 font-bold">{r.number_of_days}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${STATUS[r.status]}`}>{r.status}</span></td><td className="px-4 py-4"><button onClick={()=>setSelected(r)} className="rounded-lg border p-2"><Eye size={14}/></button></td></tr>)}</tbody></table></div><div className="divide-y lg:hidden">{rows.map(r=><button key={r.id} onClick={()=>setSelected(r)} className="w-full p-4 text-left"><div className="flex justify-between gap-3"><div><b className="text-sm">{r.staff?.full_name}</b><p className="mt-1 text-xs text-gray-500">{r.request_number} · {r.leave_type}</p><p className="mt-1 text-[10px] text-gray-400">{nice(r.from_date)} – {nice(r.to_date)} · {r.number_of_days} day(s)</p></div><span className={`h-fit rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${STATUS[r.status]}`}>{r.status}</span></div></button>)}</div></>}</div></div>{selected&&<ReviewModal row={selected} close={()=>setSelected(null)} saved={async()=>{setSelected(null);await load();}}/>}</>}
function ReviewModal({row,close,saved}:{row:LeaveRequest;close:()=>void;saved:()=>Promise<void>}){const[reason,setReason]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const decide=async(d:Extract<LeaveStatus,'Approved'|'Rejected'>)=>{if(d==='Rejected'&&!reason.trim()){setError('Enter a rejection reason.');return;}setBusy(true);setError('');try{await reviewLeave(row.id,d,reason);await saved();}catch(cause){setError(cause instanceof Error?cause.message:'Unable to review request.');}finally{setBusy(false)}};return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/55 sm:items-center sm:p-4"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 sm:max-w-2xl sm:rounded-3xl sm:p-6"><div className="flex justify-between"><div><h2 className="text-lg font-black">{row.request_number}</h2><p className="mt-1 text-xs text-gray-400">Submitted {new Date(row.created_at).toLocaleString('en-IN')}</p></div><button onClick={close} className="h-fit rounded-xl bg-gray-100 p-2"><X size={16}/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{[['Employee',`${row.staff?.full_name} (${row.staff?.employee_code})`],['Leave type',row.leave_type],['Dates',`${nice(row.from_date)} – ${nice(row.to_date)}`],['Duration',`${row.number_of_days} day(s)`],['Reason',row.reason],['Status',row.status]].map(([l,v])=><div key={l}><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">{l}</p><p className="mt-1 whitespace-pre-wrap text-sm font-semibold">{v}</p></div>)}</div>{row.attachment_path&&<button onClick={()=>openLeaveAttachment(row.attachment_path!)} className="mt-5 inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-bold"><Paperclip size={14}/> {row.attachment_name||'Open attachment'}</button>}{row.rejection_reason&&<div className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700"><b>Rejection reason:</b> {row.rejection_reason}</div>}{row.status==='Pending'&&<><label className="agreement-field mt-5"><span>Rejection reason (required only when rejecting)</span><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p className="mt-3 text-sm font-semibold text-red-600">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button disabled={busy} onClick={()=>decide('Rejected')} className="rounded-xl border border-red-200 px-4 py-2 text-xs font-bold text-red-600">Reject</button><button disabled={busy} onClick={()=>decide('Approved')} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-bold text-white">Approve leave</button></div></>}</div></div>}
