'use client';
import { CalendarClock, CheckCircle2 } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
type Details = { candidate: { name: string; position: string }; min: string; max: string };
const TIME_SLOTS = ['16:00', '16:30', '17:00', '17:30', '18:00'];
export default function ScheduleInterview({ token }: { token: string }) {
  const [details, setDetails] = useState<Details | null>(null); const [message, setMessage] = useState('Loading your scheduling link…'); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch(`/api/opportunities/schedule?token=${encodeURIComponent(token)}`).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setDetails(data); setMessage(''); }).catch(error => setMessage(error instanceof Error ? error.message : 'This scheduling link is unavailable.')); }, [token]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; const form = new FormData(event.currentTarget); const date = String(form.get('date')); const time = String(form.get('time')); if (!date || !time) return; setBusy(true); setMessage('Reserving your interview time…'); try { const response = await fetch('/api/opportunities/schedule', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token, scheduledAt: `${date}T${time}:00` }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setDetails(null); setMessage('Your interview time is confirmed. We will contact you on WhatsApp with the details.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'We could not reserve that time.'); setBusy(false); } }
  const inputDate = (value: string) => value.slice(0, 10);
  return <section className="bg-[#F8F4EE]"><div className="mx-auto max-w-xl px-5 py-14 sm:py-20"><div className="rounded-3xl border border-black/10 bg-white p-6 sm:p-10"><CalendarClock className="text-[#E30B1D]" size={28}/><p className="mt-6 text-[10px] font-extrabold uppercase tracking-[0.14em] text-[#E30B1D]">Interview scheduling</p>{details ? <><h1 className="mt-3 text-3xl font-extrabold">Choose your interview time</h1><p className="mt-3 text-sm leading-6 text-black/55">Hello {details.candidate.name}. Choose a suitable time for the {details.candidate.position} interview. Select a date within five days and a slot between 4:00 PM and 6:00 PM.</p><form onSubmit={submit} className="mt-7 grid gap-5 sm:grid-cols-2"><label className="opportunity-field"><span>Interview date <b className="ml-1 text-[#E30B1D]">*</b></span><input name="date" type="date" min={inputDate(details.min)} max={inputDate(details.max)} required/></label><label className="opportunity-field"><span>Interview time <b className="ml-1 text-[#E30B1D]">*</b></span><select name="time" required defaultValue=""><option value="" disabled>Choose a time</option>{TIME_SLOTS.map(time => <option key={time} value={time}>{new Date(`2000-01-01T${time}:00`).toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' })}</option>)}</select></label><button disabled={busy} className="sm:col-span-2 mt-1 w-full rounded-xl bg-[#E30B1D] px-5 py-3 text-sm font-extrabold text-white disabled:opacity-60">{busy ? 'Confirming…' : 'Confirm interview time'}</button></form></> : <div className="mt-5 rounded-xl bg-black/[0.035] p-4 text-sm font-semibold text-black/65"><CheckCircle2 className="mb-2 text-emerald-600" size={19}/>{message}</div>}</div></div></section>;
}
