'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarDays, CircleX, Clock3, Eye, Paperclip, Plus, X } from 'lucide-react';
import CrmHeader from '../../crm/components/CrmHeader';
import { useSidebar } from '../../crm/sidebar-context';
import type { LeaveRequest, LeaveType } from '../../crm/lib/types';
import { cancelLeave, getLeaveRequests, getMyLeaveBalances, leaveWhatsAppUrl, openLeaveAttachment, submitLeave, type LeaveBalance } from '../../crm/leave/leave-data';

const TYPES: LeaveType[] = ['Casual Leave', 'Sick Leave', 'Paid Leave', 'Unpaid Leave', 'Other'];
const STATUS: Record<string, string> = { Pending: 'bg-amber-50 text-amber-700', Approved: 'bg-emerald-50 text-emerald-700', Rejected: 'bg-red-50 text-red-700', Cancelled: 'bg-gray-100 text-gray-500' };
const today = () => new Date().toISOString().slice(0, 10);
const dayCount = (from: string, to: string) => from && to && to >= from ? Math.round((Date.parse(`${to}T00:00:00`) - Date.parse(`${from}T00:00:00`)) / 86400000) + 1 : 0;
const niceDate = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

export default function StaffLeavePage() {
  const { open } = useSidebar();
  const [rows, setRows] = useState<LeaveRequest[]>([]); const [loading, setLoading] = useState(true); const [formOpen, setFormOpen] = useState(false); const [selected, setSelected] = useState<LeaveRequest | null>(null); const [error, setError] = useState('');
  const [balances, setBalances] = useState<LeaveBalance[]>([]);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [requests, myBalances] = await Promise.all([getLeaveRequests(), getMyLeaveBalances()]); setRows(requests); setBalances(myBalances); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load leave requests.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const summary = useMemo(() => ({ pending: rows.filter(r => r.status === 'Pending').length, approved: rows.filter(r => r.status === 'Approved').reduce((n,r) => n+r.number_of_days,0), rejected: rows.filter(r => r.status === 'Rejected').length, used: rows.filter(r => r.status === 'Approved').reduce((n,r) => n+r.number_of_days,0) }), [rows]);
  const plBalance = balances.find(b => b.leave_type === 'Paid Leave')?.balance_days ?? 0;
  const slBalance = balances.find(b => b.leave_type === 'Sick Leave')?.balance_days ?? 0;
  const cancel = async (row: LeaveRequest) => { if (!window.confirm(`Cancel ${row.request_number}?`)) return; try { await cancelLeave(row.id); await load(); setSelected(null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to cancel request.'); } };
  return <><CrmHeader title="Leave" subtitle="Request leave and track every decision" onMenuClick={open} notificationsHref="/workspace/notifications" actions={<button onClick={() => setFormOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-3.5 py-2 text-xs font-bold text-white"><Plus size={15}/> Request leave</button>} />
    <div className="space-y-5 p-4 sm:p-6">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{([['Paid Leave balance',plBalance,CalendarDays,plBalance<0?'text-red-600':'text-emerald-600'],['Sick Leave balance',slBalance,CalendarDays,slBalance<0?'text-red-600':'text-emerald-600'],['Pending requests',summary.pending,Clock3,'text-amber-600'],['Rejected requests',summary.rejected,CircleX,'text-red-600']] as const).map(([label,value,Icon,tone]) => <div key={label} className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">{label}</p><Icon size={16} className={tone}/></div><p className="mt-4 text-2xl font-black text-gray-950">{value}</p></div>)}</div>
      <p className="text-xs text-gray-400">Paid Leave & Sick Leave accrue +1 day each on the 1st of every month you&apos;re active, and carry forward every year with no cap. Balance updates only when your admin approves a request — you can still submit a request even if it exceeds your current balance.</p>
      {error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
      <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="border-b border-gray-100 px-5 py-4"><h2 className="font-black">My leave history</h2><p className="mt-1 text-xs text-gray-400">Newest requests appear first</p></div>
        {loading ? <div className="flex h-56 items-center justify-center"><span className="h-7 w-7 animate-spin rounded-full border-2 border-gray-200 border-t-red-600"/></div> : !rows.length ? <div className="px-6 py-16 text-center"><CalendarDays className="mx-auto text-gray-300" size={30}/><p className="mt-3 font-bold">No leave requests yet</p><p className="mt-1 text-sm text-gray-400">Your submitted requests will appear here.</p></div> : <><div className="hidden overflow-x-auto md:block"><table className="w-full text-sm"><thead><tr className="bg-gray-50">{['Request','Type','Dates','Days','Status',''].map(h => <th key={h} className="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-widest text-gray-400">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(row => <tr key={row.id}><td className="px-5 py-4 font-bold">{row.request_number}<small className="mt-1 block font-normal text-gray-400">{niceDate(row.created_at.slice(0,10))}</small></td><td className="px-5 py-4">{row.leave_type}</td><td className="px-5 py-4 text-gray-600">{niceDate(row.from_date)} – {niceDate(row.to_date)}</td><td className="px-5 py-4 font-bold">{row.number_of_days}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${STATUS[row.status]}`}>{row.status}</span></td><td className="px-5 py-4"><button onClick={() => setSelected(row)} className="rounded-lg border p-2 text-gray-500 hover:text-red-600" aria-label="View request"><Eye size={14}/></button></td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{rows.map(row => <button key={row.id} onClick={() => setSelected(row)} className="w-full p-4 text-left"><div className="flex items-start justify-between gap-3"><div><b className="text-sm">{row.request_number}</b><p className="mt-1 text-xs text-gray-500">{row.leave_type} · {row.number_of_days} day(s)</p><p className="mt-1 text-[10px] text-gray-400">{niceDate(row.from_date)} – {niceDate(row.to_date)}</p></div><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${STATUS[row.status]}`}>{row.status}</span></div></button>)}</div></>}
      </div>
    </div>
    {formOpen && <RequestModal close={() => setFormOpen(false)} saved={async () => { setFormOpen(false); await load(); }} balances={balances}/>} {selected && <DetailModal row={selected} close={() => setSelected(null)} cancel={() => cancel(selected)}/>} </>;
}

function RequestModal({ close, saved, balances }: { close: () => void; saved: () => Promise<void>; balances: LeaveBalance[] }) {
  const [type,setType]=useState<LeaveType>('Casual Leave'); const [from,setFrom]=useState(today()); const [to,setTo]=useState(today()); const [reason,setReason]=useState(''); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const days=dayCount(from,to);
  const trackedBalance = (type==='Paid Leave'||type==='Sick Leave') ? balances.find(b=>b.leave_type===type)?.balance_days ?? 0 : null;
  const exceedsBalance = trackedBalance !== null && days > trackedBalance;
  const save=async()=>{ if(!days||!reason.trim()){setError('Select valid dates and enter a reason.');return;} const input={leaveType:type,fromDate:from,toDate:to,reason,file}; const whatsappWindow=window.open('about:blank','_blank'); setBusy(true);setError('');try{const request=await submitLeave(input);if(whatsappWindow){whatsappWindow.location.href=leaveWhatsAppUrl(input,request.request_number);}else{window.location.href=leaveWhatsAppUrl(input,request.request_number);}await saved();}catch(cause){whatsappWindow?.close();setError(cause instanceof Error?cause.message:'Unable to submit leave.');}finally{setBusy(false);}};
  return <Modal title="Request leave" close={close}><div className="grid gap-4 sm:grid-cols-2"><Field label="Leave type"><select value={type} onChange={e=>setType(e.target.value as LeaveType)}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Number of days"><input value={days||''} readOnly placeholder="Calculated automatically"/></Field><Field label="From date"><input type="date" min={today()} value={from} onChange={e=>{setFrom(e.target.value);if(e.target.value>to)setTo(e.target.value);}}/></Field><Field label="To date"><input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></Field>{trackedBalance!==null && <Field label={`Current ${type} balance`} wide><p className="rounded-xl border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm font-bold text-gray-700">{trackedBalance} day(s) available</p></Field>}{exceedsBalance && <div className="sm:col-span-2 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs font-semibold text-amber-800">This request ({days} day{days===1?'':'s'}) exceeds your available {type} balance ({trackedBalance} day{trackedBalance===1?'':'s'}). You can still submit it — it will go to your admin as a normal request, flagged as exceeding balance.</div>}<Field label="Reason" wide><textarea rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Briefly explain your leave request"/></Field><Field label="Supporting file (optional — not uploaded)" wide><input type="file" accept=".pdf,.png,.jpg,.jpeg,.doc,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/><small className="mt-2 block text-[11px] leading-5 text-gray-500">The file is never stored in Supabase. After the request is saved, WhatsApp opens for 8830612287; attach this file there before sending.</small></Field></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={close} className="rounded-xl border px-4 py-2 text-xs font-bold">Cancel</button><button onClick={save} disabled={busy} className="rounded-xl bg-red-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{busy?'Submitting…':'Submit & open WhatsApp'}</button></div></Modal>;
}
function DetailModal({row,close,cancel}:{row:LeaveRequest;close:()=>void;cancel:()=>void}){return <Modal title={row.request_number} close={close}><div className="grid gap-4 sm:grid-cols-2"><Info label="Status" value={row.status}/><Info label="Leave type" value={row.leave_type}/><Info label="Dates" value={`${niceDate(row.from_date)} – ${niceDate(row.to_date)}`}/><Info label="Duration" value={`${row.number_of_days} day(s)`}/><Info label="Reason" value={row.reason} wide/>{row.rejection_reason&&<Info label="Rejection reason" value={row.rejection_reason} wide/>}{row.reviewed_by_name&&<Info label="Reviewed by" value={`${row.reviewed_by_name}${row.reviewed_at?` · ${new Date(row.reviewed_at).toLocaleString('en-IN')}`:''}`} wide/>}</div><div className="mt-5 flex flex-wrap justify-end gap-2">{row.attachment_path&&<button onClick={()=>openLeaveAttachment(row.attachment_path!)} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-bold"><Paperclip size={14}/> {row.attachment_name||'Attachment'}</button>}{row.status==='Pending'&&<button onClick={cancel} className="rounded-xl bg-red-600 px-4 py-2 text-xs font-bold text-white">Cancel request</button>}</div></Modal>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/55 p-0 sm:items-center sm:p-4" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:max-w-2xl sm:rounded-3xl sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-black">{title}</h2><button onClick={close} className="rounded-xl bg-gray-100 p-2"><X size={16}/></button></div>{children}</div></div>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={`agreement-field ${wide?'sm:col-span-2':''}`}><span>{label}</span>{children}</label>}
function Info({label,value,wide}:{label:string;value:string;wide?:boolean}){return <div className={wide?'sm:col-span-2':''}><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm font-semibold text-gray-800">{value}</p></div>}
