'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { ArrowLeft, Banknote, Check, Download, FilePenLine, FileText, Loader2, Mail, MessageCircle, Printer, ReceiptText, Send, XCircle } from 'lucide-react';
import QRCode from 'qrcode';
import CrmHeader from '../../components/CrmHeader';
import { useSidebar } from '../../sidebar-context';
import type { InvoicePayment, InvoiceRecord, InvoiceStatus } from '../../lib/types';
import InvoiceDocument from '../components/InvoiceDocument';
import PaymentReceiptDocument from '../components/PaymentReceiptDocument';
import { addInvoicePayment, getInvoiceById, updateInvoice, updateInvoicePayment } from '../invoice-data';
import { currency, effectiveInvoiceStatus, formatInvoiceDate, getBusinessProfile, PAYMENT_MODES } from '../invoice-config';

export default function InvoiceDetailPage() {
  const { open } = useSidebar(); const params = useParams<{id:string}>(); const previewRef = useRef<HTMLDivElement>(null);
  const [invoice,setInvoice]=useState<InvoiceRecord|null>(null); const [qr,setQr]=useState(''); const [busy,setBusy]=useState(''); const [notice,setNotice]=useState(''); const [showPayment,setShowPayment]=useState(false); const [editingPaymentId,setEditingPaymentId]=useState('');
  const currentProfile=useMemo(()=>getBusinessProfile(),[]);
  const [payment,setPayment]=useState({payment_date:new Date().toISOString().slice(0,10),amount:0,payment_mode:'UPI',transaction_reference:'',notes:'',recorded_by:'CRM Administrator'});
  useEffect(()=>{getInvoiceById(params.id).then(setInvoice)},[params.id]);
  useEffect(()=>{if(invoice) QRCode.toDataURL(`${window.location.origin}/verify/${invoice.verification_code}`,{width:128,margin:0}).then(setQr)},[invoice]);
  useEffect(()=>{if(invoice) setPayment(p=>({...p,amount:invoice.balance_due}))},[invoice]);
  const notify=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(''),3000)};
  const makePdf=async(element:HTMLElement,filename:string,title:string)=>{const [{default:html2canvas},{jsPDF}]=await Promise.all([import('html2canvas'),import('jspdf')]);const canvas=await html2canvas(element,{scale:2,useCORS:true,backgroundColor:'#fff',logging:false,windowWidth:794});const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});pdf.addImage(canvas.toDataURL('image/jpeg',.95),'JPEG',0,0,210,297,undefined,'FAST');pdf.setProperties({title,author:'PlanMyBaraat',creator:'PlanMyBaraat CRM'});pdf.save(filename)};
  const downloadInvoice=async()=>{if(!invoice||!previewRef.current)return;setBusy('invoice');try{const page=previewRef.current.querySelector<HTMLElement>('.invoice-pdf-page');if(!page)throw new Error('Preview unavailable');await makePdf(page,`${invoice.invoice_number.replace(/[^a-z0-9]+/gi,'-')}-${invoice.client_name.replace(/[^a-z0-9]+/gi,'-')}.pdf`,invoice.invoice_number);notify('Invoice PDF downloaded.')}catch(e){notify(e instanceof Error?e.message:'Export failed.')}finally{setBusy('')}};
  const downloadReceipt=async(entry:InvoicePayment)=>{setBusy(entry.id);try{const el=document.getElementById(`payment-receipt-${entry.id}`);if(!el)throw new Error('Receipt unavailable');await makePdf(el,`${entry.receipt_number.replace(/[^a-z0-9]+/gi,'-')}.pdf`,entry.receipt_number);notify('Payment receipt downloaded.')}finally{setBusy('')}};
  const changeStatus=async(status:InvoiceStatus)=>{if(!invoice)return;setBusy('status');try{setInvoice(await updateInvoice(invoice.id,{...invoice,status}));notify(`Invoice marked ${status}.`)}finally{setBusy('')}};
  const openPayment=(entry?:InvoicePayment)=>{setEditingPaymentId(entry?.id||'');setPayment(entry?{payment_date:entry.payment_date,amount:entry.amount,payment_mode:entry.payment_mode,transaction_reference:entry.transaction_reference,notes:entry.notes,recorded_by:entry.recorded_by}:{payment_date:new Date().toISOString().slice(0,10),amount:invoice?.balance_due||0,payment_mode:'UPI',transaction_reference:'',notes:'',recorded_by:'CRM Administrator'});setShowPayment(true)};
  const recordPayment=async(e:React.FormEvent)=>{e.preventDefault();const old=invoice?.payments.find(item=>item.id===editingPaymentId);if(!invoice||payment.amount<=0||payment.amount>invoice.balance_due+(old?.amount||0)){notify('Enter an amount up to the available balance.');return}setBusy('payment');try{setInvoice(editingPaymentId?await updateInvoicePayment(invoice.id,editingPaymentId,payment):await addInvoicePayment(invoice.id,payment));setShowPayment(false);notify(editingPaymentId?'Payment updated.':'Payment recorded and receipt created.');setEditingPaymentId('')}finally{setBusy('')}};
  if(!invoice)return <><CrmHeader title="Invoice" subtitle="Loading commercial document" onMenuClick={open}/><div className="flex h-96 items-center justify-center"><Loader2 className="animate-spin text-red-600"/></div></>;
  const status=effectiveInvoiceStatus(invoice); const tones:Record<InvoiceStatus,string>={Draft:'bg-gray-100 text-gray-700',Issued:'bg-blue-50 text-blue-700','Partially Paid':'bg-amber-50 text-amber-700',Paid:'bg-emerald-50 text-emerald-700',Overdue:'bg-red-50 text-red-700',Cancelled:'bg-gray-100 text-gray-500'};
  return <>
    <CrmHeader title={invoice.invoice_number} subtitle={`${invoice.client_name} · ${invoice.document_type}`} onMenuClick={open} actions={<Link href="/crm/invoices" className="invoice-action-button"><ArrowLeft size={15}/> Invoices</Link>}/>
    {notice&&<div className="fixed right-5 top-5 z-[80] rounded-xl bg-gray-950 px-4 py-3 text-xs font-bold text-white shadow-2xl">{notice}</div>}
    <div className="space-y-5 p-4 sm:p-6">
      <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black text-gray-950">{invoice.client_name}</h2><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${tones[status]}`}>{status}</span></div><p className="mt-1 text-sm text-gray-400">{invoice.agreement_number} · {formatInvoiceDate(invoice.event_date)} · {invoice.package_name}</p></div><div className="grid grid-cols-3 gap-4"><Summary label="Total" value={currency(invoice.total_amount)}/><Summary label="Paid" value={currency(invoice.amount_paid)} tone="text-emerald-600"/><Summary label="Balance" value={currency(invoice.balance_due)} tone="text-red-600"/></div></div>
      <div className="mt-5 flex flex-wrap gap-2 border-t border-gray-100 pt-5"><Link href={`/crm/invoices/new?edit=${invoice.id}`} className="invoice-action-button"><FilePenLine size={15}/>Edit</Link><button onClick={downloadInvoice} className="invoice-action-primary"><Download size={15}/>{busy==='invoice'?'Preparing...':'Download PDF'}</button><button onClick={()=>window.print()} className="invoice-action-button"><Printer size={15}/>Print</button><button onClick={()=>{window.location.href=`mailto:${invoice.email}?subject=${encodeURIComponent(invoice.invoice_number+' | PlanMyBaraat')}&body=${encodeURIComponent(`Dear ${invoice.client_name},\n\nPlease find your ${invoice.document_type}. Balance due: ${currency(invoice.balance_due)}.\n\nPlanMyBaraat`)}`}} className="invoice-action-button"><Mail size={15}/>Email</button><button onClick={()=>window.open(`https://wa.me/${invoice.mobile.replace(/\D/g,'')}?text=${encodeURIComponent(`Hello ${invoice.client_name}, your ${invoice.document_type} ${invoice.invoice_number} is ready. Balance: ${currency(invoice.balance_due)}.`)}`,'_blank','noopener,noreferrer')} className="invoice-action-button"><MessageCircle size={15}/>WhatsApp</button>{invoice.balance_due>0&&<button onClick={()=>openPayment()} className="invoice-action-button"><Banknote size={15}/>Record payment</button>}{invoice.status==='Draft'&&<button onClick={()=>changeStatus('Issued')} className="invoice-action-button"><Send size={15}/>Issue</button>}{!['Paid','Cancelled'].includes(invoice.status)&&<button onClick={()=>changeStatus('Cancelled')} className="invoice-action-button text-red-600"><XCircle size={15}/>Cancel</button>}</div></section>
      <section className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4 flex justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-gray-950">Live PDF preview</p><p className="mt-1 text-xs text-gray-400">Same typography and branding as your agreement.</p></div><FileText size={18} className="text-red-600"/></div><div className="invoice-preview-scroll"><div ref={previewRef}><InvoiceDocument invoice={invoice} profile={invoice.supplier_profile || currentProfile} qr={qr}/></div></div></section>
      <section className="rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-gray-100 p-5"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-red-600">Payment ledger</p><h3 className="mt-1 text-lg font-black">Receipts and transactions</h3></div><ReceiptText className="text-gray-300"/></div>{invoice.payments.length===0?<div className="p-10 text-center text-sm text-gray-400">No individual payments recorded on this invoice yet.</div>:<div className="divide-y divide-gray-100">{invoice.payments.map(entry=><div key={entry.id} className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div><p className="font-mono text-xs font-black">{entry.receipt_number}</p><p className="mt-1 text-xs text-gray-400">{formatInvoiceDate(entry.payment_date)} · {entry.payment_mode}{entry.transaction_reference?` · ${entry.transaction_reference}`:''}</p></div><div className="flex items-center gap-2"><strong className="mr-2 text-lg font-black text-emerald-600">{currency(entry.amount)}</strong><button onClick={()=>openPayment(entry)} className="invoice-action-button"><FilePenLine size={14}/>Edit</button><button onClick={()=>downloadReceipt(entry)} className="invoice-action-button"><Download size={14}/>{busy===entry.id?'Preparing...':'Receipt'}</button></div></div>)}</div>}</section>
    </div>
    <div className="invoice-receipt-render-zone">{invoice.payments.map(entry=><PaymentReceiptDocument key={entry.id} invoice={invoice} payment={entry} profile={invoice.supplier_profile || currentProfile}/>)}</div>
    {showPayment&&<div className="fixed inset-0 z-[70] flex items-end justify-center bg-black/60 sm:items-center sm:p-4"><form onSubmit={recordPayment} className="w-full max-w-lg rounded-t-3xl bg-white p-5 sm:rounded-2xl sm:p-6"><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase tracking-widest text-red-600">Record payment</p><h3 className="mt-1 text-xl font-black">Create payment receipt</h3><p className="mt-1 text-sm text-gray-400">Balance {currency(invoice.balance_due)}</p></div><button type="button" onClick={()=>setShowPayment(false)}><XCircle className="text-gray-400"/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Payment date"><input type="date" value={payment.payment_date} onChange={e=>setPayment(p=>({...p,payment_date:e.target.value}))}/></Field><Field label="Amount"><input type="number" min=".01" max={invoice.balance_due} step=".01" value={payment.amount} onChange={e=>setPayment(p=>({...p,amount:Number(e.target.value)}))}/></Field><Field label="Payment mode"><select value={payment.payment_mode} onChange={e=>setPayment(p=>({...p,payment_mode:e.target.value}))}>{PAYMENT_MODES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Transaction reference"><input value={payment.transaction_reference} onChange={e=>setPayment(p=>({...p,transaction_reference:e.target.value}))}/></Field><label className="agreement-field sm:col-span-2"><span>Note</span><textarea rows={3} value={payment.notes} onChange={e=>setPayment(p=>({...p,notes:e.target.value}))}/></label></div><button type="submit" className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 px-5 py-3 text-sm font-bold text-white"><Check size={16}/>{busy==='payment'?'Recording...':'Record payment & create receipt'}</button></form></div>}
  </>;
}
function Summary({label,value,tone='text-gray-950'}:{label:string;value:string;tone?:string}){return <div><span className="text-[9px] font-bold uppercase tracking-widest text-gray-400">{label}</span><p className={`mt-1 font-black ${tone}`}>{value}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="agreement-field"><span>{label}</span>{children}</label>}
