'use client';

import { useEffect,useState } from 'react';
import { Coffee,Plus,Save,Trash2,X } from 'lucide-react';
import type { AttendanceRecord } from '../../lib/types';
import { adminSaveAttendanceBreaks } from '../../lib/attendance-policy';

type Draft={start:string;end:string};
const localInput=(value:string|null|undefined)=>value?new Date(value).toLocaleString('sv-SE',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).replace(' ','T'):'';
const iso=(value:string)=>value?new Date(value).toISOString():'';

export default function BreakCorrectionModal({row,onClose,onSaved}:{row:AttendanceRecord|null;onClose:()=>void;onSaved:()=>void|Promise<void>}){
 const [items,setItems]=useState<Draft[]>([]);const [reason,setReason]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(row){setItems((row.breaks||[]).filter(item=>item.break_end_at).map(item=>({start:localInput(item.break_start_at),end:localInput(item.break_end_at)})));setReason('');setError('');}},[row]);
 if(!row)return null;
 const add=()=>{const base=`${row.attendance_date}T13:00`;setItems(current=>[...current,{start:base,end:`${row.attendance_date}T13:15`}]);};
 const submit=async()=>{if(!row.id)return;if(reason.trim().length<3){setError('Enter a correction reason.');return;}if(items.some(item=>!item.start||!item.end||new Date(item.end)<new Date(item.start))){setError('Every break requires a valid start and end time.');return;}setSaving(true);setError('');try{await adminSaveAttendanceBreaks(row.id,items.map(item=>({break_start_at:iso(item.start),break_end_at:iso(item.end)})),reason);await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save break corrections.');}finally{setSaving(false);}};
 return <div className="fixed inset-0 z-[90] flex items-end justify-center bg-gray-950/50 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:max-w-xl sm:rounded-3xl"><div className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-gray-100 bg-white px-5 py-4"><div><p className="flex items-center gap-2 font-black"><Coffee size={17} className="text-red-600"/>Correct Break Records</p><p className="mt-1 text-xs text-gray-400">{row.staff?.full_name} · {row.attendance_date}</p></div><button onClick={onClose} className="rounded-xl border border-gray-200 p-2 text-gray-400"><X size={16}/></button></div><div className="space-y-4 p-5">{items.map((item,index)=><div key={index} className="rounded-2xl border border-gray-200 p-4"><div className="mb-3 flex items-center justify-between"><b className="text-xs">Break {index+1}</b><button onClick={()=>setItems(current=>current.filter((_,i)=>i!==index))} className="rounded-lg p-1.5 text-gray-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={14}/></button></div><div className="grid gap-3 sm:grid-cols-2"><label className="agreement-field"><span>Start</span><input type="datetime-local" value={item.start} onChange={event=>setItems(current=>current.map((value,i)=>i===index?{...value,start:event.target.value}:value))}/></label><label className="agreement-field"><span>End</span><input type="datetime-local" value={item.end} onChange={event=>setItems(current=>current.map((value,i)=>i===index?{...value,end:event.target.value}:value))}/></label></div></div>)}{!items.length&&<div className="rounded-2xl border border-dashed border-gray-200 py-8 text-center text-xs text-gray-400">No completed breaks recorded.</div>}<button onClick={add} className="flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-gray-300 px-4 py-3 text-xs font-bold text-gray-600"><Plus size={15}/>Add break</button><label className="agreement-field"><span>Correction reason *</span><input value={reason} onChange={event=>setReason(event.target.value)} placeholder="Why are these break records being corrected?"/></label>{error&&<p className="rounded-xl border border-red-200 bg-red-50 px-3 py-2.5 text-xs font-semibold text-red-700">{error}</p>}</div><div className="sticky bottom-0 flex justify-end gap-2 border-t border-gray-100 bg-white px-5 py-4"><button onClick={onClose} className="rounded-xl border border-gray-200 px-4 py-2.5 text-xs font-bold">Cancel</button><button disabled={saving} onClick={submit} className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50"><Save size={14}/>{saving?'Saving...':'Save correction'}</button></div></div></div>;
}
