'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { CircleDollarSign, FileText, Filter, Pencil, Plus, Search, Send, Trash2, TrendingUp, X } from 'lucide-react';
import CrmHeader from '../components/CrmHeader';
import ConfirmDialog from '../components/ConfirmDialog';
import { useSidebar } from '../sidebar-context';
import type { QuotationFilters, QuotationRecord, QuotationStatus } from '../lib/types';
import { deleteQuotation, getQuotations } from './quotation-data';
import { formatQuotationDate, quotationCurrency, QUOTATION_PACKAGES, QUOTATION_STATUSES } from './quotation-config';

const TONES: Record<QuotationStatus, string> = { Draft: 'bg-gray-100 text-gray-700', Sent: 'bg-blue-50 text-blue-700', Negotiation: 'bg-amber-50 text-amber-700', Accepted: 'bg-emerald-50 text-emerald-700', Rejected: 'bg-red-50 text-red-700', Expired: 'bg-orange-50 text-orange-700', Converted: 'bg-violet-50 text-violet-700' };

export default function QuotationsPage() {
  const { open } = useSidebar(); const router = useRouter();
  const [items, setItems] = useState<QuotationRecord[]>([]); const [loading, setLoading] = useState(true); const [filtersOpen, setFiltersOpen] = useState(false); const [target, setTarget] = useState<QuotationRecord | null>(null); const [error, setError] = useState('');
  const [filters, setFilters] = useState<QuotationFilters>({ search: '', status: '', package_name: '', event_date_from: '', event_date_to: '' });
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(await getQuotations(filters)); } catch (cause) { setItems([]); setError(cause instanceof Error ? cause.message : 'Unable to load quotations.'); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { const timer = window.setTimeout(load, 200); return () => window.clearTimeout(timer); }, [load]);
  const stats = useMemo(() => { const accepted = items.filter(item => ['Accepted', 'Converted'].includes(item.status)); const sent = items.filter(item => item.status !== 'Draft'); return { total: items.length, awaiting: items.filter(item => ['Sent', 'Negotiation'].includes(item.status)).length, value: accepted.reduce((sum, item) => sum + item.total_amount, 0), conversion: sent.length ? Math.round(accepted.length / sent.length * 100) : 0 }; }, [items]);
  const clear = () => setFilters({ search: '', status: '', package_name: '', event_date_from: '', event_date_to: '' });
  const remove = async () => { if (!target) return; setError(''); try { await deleteQuotation(target.id); setTarget(null); await load(); } catch (cause) { setTarget(null); setError(cause instanceof Error ? cause.message : 'Unable to delete quotation.'); } };

  return <><CrmHeader title="Client Quotations" subtitle="Build, present and convert tailored Baraat proposals" onMenuClick={open} actions={<Link href="/crm/quotations/new" className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-3.5 py-2 text-xs font-bold text-white"><Plus size={15} /> <span className="hidden sm:inline">Create quotation</span></Link>} />
    <div className="space-y-5 p-4 sm:p-6">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[
        ['Total quotations', String(stats.total), FileText, 'bg-gray-950 text-white'], ['Awaiting response', String(stats.awaiting), Send, 'bg-white text-gray-950'], ['Accepted value', quotationCurrency(stats.value), CircleDollarSign, 'bg-red-600 text-white'], ['Conversion rate', `${stats.conversion}%`, TrendingUp, 'bg-white text-gray-950'],
      ].map(([label, value, Icon, tone]) => <div key={String(label)} className={`rounded-2xl border border-gray-200 p-4 shadow-sm sm:p-5 ${tone}`}><div className="flex justify-between"><p className="text-[10px] font-bold uppercase tracking-widest opacity-60">{String(label)}</p><Icon size={16} className="opacity-60" /></div><p className="mt-4 truncate text-xl font-black sm:text-2xl">{String(value)}</p></div>)}</div>
      <div className="flex flex-wrap gap-2"><div className="relative min-w-[220px] flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" /><input className="w-full rounded-xl border border-gray-200 bg-white py-2.5 pl-9 pr-4 text-sm outline-none focus:border-red-400" placeholder="Search quotation, client or mobile..." value={filters.search} onChange={event => setFilters(current => ({ ...current, search: event.target.value }))} /></div><button onClick={() => setFiltersOpen(value => !value)} className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-xs font-bold"><Filter size={15} /> Filters</button>{Object.values(filters).some(Boolean) && <button onClick={clear} className="inline-flex items-center gap-1 px-2 text-xs font-bold text-gray-400"><X size={14} /> Clear</button>}</div>
      {filtersOpen && <div className="grid gap-4 rounded-2xl border border-gray-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="agreement-field"><span>Status</span><select value={filters.status} onChange={event => setFilters(current => ({ ...current, status: event.target.value }))}><option value="">All statuses</option>{QUOTATION_STATUSES.map(value => <option key={value}>{value}</option>)}</select></label><label className="agreement-field"><span>Package</span><select value={filters.package_name} onChange={event => setFilters(current => ({ ...current, package_name: event.target.value }))}><option value="">All packages</option>{QUOTATION_PACKAGES.map(value => <option key={value}>{value}</option>)}</select></label><label className="agreement-field"><span>Event from</span><input type="date" value={filters.event_date_from} onChange={event => setFilters(current => ({ ...current, event_date_from: event.target.value }))} /></label><label className="agreement-field"><span>Event to</span><input type="date" value={filters.event_date_to} onChange={event => setFilters(current => ({ ...current, event_date_to: event.target.value }))} /></label></div>}
      {error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
      <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">{loading ? <div className="flex h-60 items-center justify-center"><span className="h-7 w-7 animate-spin rounded-full border-2 border-gray-200 border-t-red-600" /></div> : !items.length ? <div className="px-6 py-20 text-center"><FileText className="mx-auto text-red-600" size={30} /><p className="mt-4 font-black">No quotations found</p><p className="mt-1 text-sm text-gray-400">{error ? 'Resolve the error above, then try again.' : 'Create a tailored proposal from your existing package and service catalogue.'}</p>{!error && <Link href="/crm/quotations/new" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-red-600 px-5 py-2.5 text-xs font-bold text-white"><Plus size={14} /> Create quotation</Link>}</div> : <>
        <div className="hidden overflow-x-auto md:block"><table className="w-full text-sm"><thead><tr className="border-b bg-gray-50/80">{['Quotation', 'Client', 'Event', 'Package', 'Value', 'Status', ''].map(value => <th key={value} className="px-4 py-3.5 text-left text-[10px] font-bold uppercase tracking-widest text-gray-400">{value}</th>)}</tr></thead><tbody className="divide-y">{items.map(item => <tr key={item.id} className="hover:bg-gray-50"><td className="px-4 py-4"><button onClick={() => router.push(`/crm/quotations/${item.id}`)} className="text-left"><b className="font-mono text-xs">{item.quotation_number}</b><small className="mt-1 block text-gray-400">Version {item.version}</small></button></td><td className="px-4 py-4"><b>{item.client_name}</b><small className="mt-1 block text-gray-400">{item.mobile}</small></td><td className="px-4 py-4"><b>{formatQuotationDate(item.event_date)}</b><small className="mt-1 block max-w-[150px] truncate text-gray-400">{item.venue}</small></td><td className="px-4 py-4 text-xs font-semibold">{item.package_name}</td><td className="px-4 py-4 font-black">{quotationCurrency(item.total_amount)}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${TONES[item.status]}`}>{item.status}</span></td><td className="px-4 py-4"><div className="flex gap-1"><Link href={`/crm/quotations/${item.id}/edit`} className="rounded-lg p-2 text-gray-400 hover:bg-gray-100"><Pencil size={15} /></Link><button onClick={() => setTarget(item)} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div>
        <div className="divide-y md:hidden">{items.map(item => <button key={item.id} onClick={() => router.push(`/crm/quotations/${item.id}`)} className="block w-full p-4 text-left"><div className="flex justify-between gap-3"><div><p className="font-mono text-[11px] font-black text-red-600">{item.quotation_number}</p><p className="mt-1 font-extrabold">{item.client_name}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[9px] font-black uppercase ${TONES[item.status]}`}>{item.status}</span></div><div className="mt-3 flex justify-between text-xs"><span className="text-gray-500">{formatQuotationDate(item.event_date)} · {item.package_name}</span><b>{quotationCurrency(item.total_amount)}</b></div></button>)}</div></>}</div>
    </div><ConfirmDialog open={!!target} title="Delete Quotation" message={`Delete ${target?.quotation_number}? Its revisions and activity will also be removed.`} confirmLabel="Delete quotation" onConfirm={remove} onCancel={() => setTarget(null)} /></>;
}
