'use client';

import { useEffect, useMemo, useState } from 'react';
import { BadgeIndianRupee, Check, ChevronLeft, ChevronRight, CircleAlert, ClipboardList, FileText, Plus, Save, Sparkles, Users } from 'lucide-react';
import type { QuotationFormData, QuotationService } from '../../lib/types';
import { PACKAGE_DEFAULTS } from '../../agreements/agreement-config';
import { QUOTATION_PACKAGES, calculateQuotationAmounts, createQuotationService, quotationCurrency } from '../quotation-config';
import QuotationServiceBlock from './QuotationServiceBlock';

const STEPS = [
  { label: 'Client', icon: Users }, { label: 'Package', icon: BadgeIndianRupee }, { label: 'Services', icon: Sparkles },
  { label: 'Commercial', icon: ClipboardList }, { label: 'Review', icon: FileText },
] as const;

const Field = ({ label, required, children, className = '' }: { label: string; required?: boolean; children: React.ReactNode; className?: string }) => <label className={`agreement-field ${className}`}><span>{label}{required && <b>*</b>}</span>{children}</label>;
const Heading = ({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) => <div className="mb-6"><p className="text-[10px] font-black uppercase tracking-[.22em] text-red-600">{eyebrow}</p><h2 className="mt-2 text-xl font-extrabold tracking-tight text-gray-950 sm:text-2xl">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-gray-500">{copy}</p></div>;

export default function QuotationForm({ initialData, onSubmit, submitLabel = 'Generate quotation' }: { initialData: QuotationFormData; onSubmit: (data: QuotationFormData) => Promise<void>; submitLabel?: string }) {
  const [data, setData] = useState(initialData);
  const [step, setStep] = useState(0);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [draftSaved, setDraftSaved] = useState(false);
  const amounts = useMemo(() => calculateQuotationAmounts(data), [data]);
  const enabledCount = data.services.filter(service => service.enabled).length;

  useEffect(() => { const timer = window.setTimeout(() => { localStorage.setItem('crm_quotation_working_draft_v1', JSON.stringify(data)); setDraftSaved(true); window.setTimeout(() => setDraftSaved(false), 1200); }, 700); return () => window.clearTimeout(timer); }, [data]);
  const text = (key: keyof QuotationFormData, value: string) => setData(current => ({ ...current, [key]: value }));
  const number = (key: 'package_price' | 'discount' | 'gst_percent' | 'suggested_booking_amount', value: string) => setData(current => ({ ...current, [key]: Math.max(0, Number(value) || 0) }));
  const updateService = (updated: QuotationService) => setData(current => ({ ...current, services: current.services.map(service => service.id === updated.id ? updated : service) }));

  const applyPackage = (packageName: QuotationFormData['package_name']) => {
    const preset = PACKAGE_DEFAULTS[packageName];
    setData(current => ({ ...current, package_name: packageName, package_price: preset.price, services: current.services.map(service => ({ ...service, enabled: preset.services.includes(service.name) || Boolean(service.is_custom && service.enabled), is_addon: service.is_custom ? service.is_addon : false })) }));
  };

  const validate = (target = step) => {
    if (target === 0 && (!data.client_name.trim() || !data.mobile.trim() || !data.event_date || !data.venue.trim())) { setError('Client name, mobile, event date and venue are required.'); return false; }
    if (target === 1 && (!data.valid_until || data.package_price < 0)) { setError('Choose a package, validity date and valid package value.'); return false; }
    if (target === 2 && enabledCount === 0) { setError('Enable at least one service.'); return false; }
    if (target === 2 && data.pricing_mode === 'Detailed Pricing' && data.services.some(service => service.enabled && service.unit_price <= 0)) { setError('Enter a price for every enabled service in Detailed Pricing mode.'); return false; }
    setError(''); return true;
  };
  const next = () => { if (!validate()) return; setStep(current => Math.min(STEPS.length - 1, current + 1)); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const submit = async () => {
    for (const required of [0, 1, 2]) if (!validate(required)) { setStep(required); return; }
    setSaving(true);
    try {
      const normalizedServices = data.services.map(service => amounts.services.find(item => item.id === service.id) ?? service);
      await onSubmit({ ...data, services: normalizedServices, subtotal: amounts.subtotal, discount: amounts.discount, taxable_value: amounts.taxableValue, gst_amount: amounts.gstAmount, total_amount: amounts.totalAmount });
      localStorage.removeItem('crm_quotation_working_draft_v1');
    } catch (cause) { setError(cause instanceof Error ? cause.message : cause && typeof cause === 'object' && 'message' in cause ? String(cause.message) : 'Unable to save quotation.'); }
    finally { setSaving(false); }
  };

  return <div className="mx-auto max-w-6xl">
    <div className="mb-5 rounded-2xl border border-gray-200 bg-white p-2 shadow-sm"><div className="grid grid-cols-3 gap-1 sm:grid-cols-5">{STEPS.map(({ label, icon: Icon }, index) => <button key={label} type="button" onClick={() => setStep(index)} className={`flex min-w-0 items-center gap-2 rounded-xl px-2 py-2.5 text-left ${index === step ? 'bg-gray-950 text-white' : 'text-gray-500 hover:bg-gray-50'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-lg ${index === step ? 'bg-red-600 text-white' : index < step ? 'bg-emerald-50 text-emerald-600' : 'bg-gray-100'}`}>{index < step ? <Check size={14} /> : <Icon size={14} />}</span><span><small className="block text-[9px] font-bold uppercase opacity-60">0{index + 1}</small><b className="block truncate text-[11px] sm:text-xs">{label}</b></span></button>)}</div></div>
    <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="p-5 sm:p-7 lg:p-9">
      {step === 0 && <><Heading eyebrow="01 / Client & event" title="Who is receiving this quotation?" copy="Capture the client and event context. Optional empty fields stay hidden in the quotation PDF." /><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <Field label="Client name" required><input value={data.client_name} onChange={e => text('client_name', e.target.value)} /></Field><Field label="Groom name"><input value={data.groom_name} onChange={e => text('groom_name', e.target.value)} /></Field><Field label="Bride name"><input value={data.bride_name} onChange={e => text('bride_name', e.target.value)} /></Field>
        <Field label="Mobile" required><input type="tel" value={data.mobile} onChange={e => text('mobile', e.target.value)} /></Field><Field label="Alternate mobile"><input value={data.alternate_mobile} onChange={e => text('alternate_mobile', e.target.value)} /></Field><Field label="Email"><input type="email" value={data.email} onChange={e => text('email', e.target.value)} /></Field>
        <Field label="Address" className="sm:col-span-2 lg:col-span-3"><textarea rows={2} value={data.address} onChange={e => text('address', e.target.value)} /></Field><Field label="Event date" required><input type="date" value={data.event_date} onChange={e => text('event_date', e.target.value)} /></Field><Field label="Venue" required><input value={data.venue} onChange={e => text('venue', e.target.value)} /></Field><Field label="Sales executive"><input value={data.sales_executive} onChange={e => text('sales_executive', e.target.value)} /></Field><Field label="Start time"><input type="time" value={data.start_time} onChange={e => text('start_time', e.target.value)} /></Field><Field label="End time"><input type="time" value={data.end_time} onChange={e => text('end_time', e.target.value)} /></Field>
      </div></>}
      {step === 1 && <><Heading eyebrow="02 / Package strategy" title="Start with a package, then customize it." copy="Package Pricing shows one base value plus add-ons. Detailed Pricing itemizes every enabled service." /><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{QUOTATION_PACKAGES.map(packageName => <button type="button" key={packageName} onClick={() => applyPackage(packageName)} className={`rounded-2xl border p-4 text-left ${data.package_name === packageName ? 'border-red-600 bg-red-50 ring-2 ring-red-100' : 'border-gray-200 hover:bg-gray-50'}`}><span className={`flex h-8 w-8 items-center justify-center rounded-xl text-xs font-black ${data.package_name === packageName ? 'bg-red-600 text-white' : 'bg-gray-100 text-gray-500'}`}>{packageName[0]}</span><b className="mt-3 block text-xs text-gray-950">{packageName}</b><small className="mt-1 block text-gray-400">{PACKAGE_DEFAULTS[packageName].price ? quotationCurrency(PACKAGE_DEFAULTS[packageName].price) : 'Build your own'}</small></button>)}</div><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Field label="Pricing display"><select value={data.pricing_mode} onChange={e => text('pricing_mode', e.target.value)}><option>Package Pricing</option><option>Detailed Pricing</option></select></Field><Field label="Base package price"><input type="number" min="0" value={data.package_price} onChange={e => number('package_price', e.target.value)} disabled={data.pricing_mode === 'Detailed Pricing'} /></Field><Field label="Valid until" required><input type="date" value={data.valid_until} min={data.created_date} onChange={e => text('valid_until', e.target.value)} /></Field><Field label="Quotation owner"><input value={data.created_by_name} onChange={e => text('created_by_name', e.target.value)} /></Field></div></>}
      {step === 2 && <><Heading eyebrow="03 / Services & add-ons" title="Configure the complete Baraat experience." copy="This is the same service catalogue used by Agreements. Enable services, select options, set quantities and price add-ons." /><div className="mb-4 mt-6 rounded-xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-xs font-semibold text-emerald-800">{enabledCount} services enabled · internal notes remain private</div><div className="space-y-3">{data.services.map(service => <QuotationServiceBlock key={service.id} service={service} pricingMode={data.pricing_mode} onChange={updateService} onRemove={service.is_custom ? () => setData(current => ({ ...current, services: current.services.filter(item => item.id !== service.id) })) : undefined} />)}</div><button type="button" onClick={() => setData(current => ({ ...current, services: [...current.services, createQuotationService('Other Service', true, true)] }))} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-gray-300 px-4 py-3 text-xs font-bold text-gray-600 hover:border-red-300 hover:bg-red-50 hover:text-red-700"><Plus size={15} /> Add custom service</button></>}
      {step === 3 && <><Heading eyebrow="04 / Commercial terms" title="Set the final commercial position." copy="Taxes and totals calculate automatically from the package and enabled add-ons." /><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Field label="Discount"><input type="number" min="0" max={amounts.subtotal} value={data.discount} onChange={e => number('discount', e.target.value)} /></Field><Field label="GST %"><input type="number" min="0" max="100" value={data.gst_percent} onChange={e => number('gst_percent', e.target.value)} /></Field><Field label="Suggested booking amount"><input type="number" min="0" max={amounts.totalAmount} value={data.suggested_booking_amount} onChange={e => number('suggested_booking_amount', e.target.value)} /></Field><Field label="Client note" className="sm:col-span-2 lg:col-span-3"><textarea rows={2} value={data.client_note} onChange={e => text('client_note', e.target.value)} /></Field><Field label="Special requirements" className="sm:col-span-2 lg:col-span-3"><textarea rows={2} value={data.special_requirements} onChange={e => text('special_requirements', e.target.value)} /></Field><Field label="Payment terms" className="sm:col-span-2 lg:col-span-3"><textarea rows={3} value={data.payment_terms} onChange={e => text('payment_terms', e.target.value)} /></Field><Field label="Exclusions" className="sm:col-span-2 lg:col-span-3"><textarea rows={3} value={data.exclusions} onChange={e => text('exclusions', e.target.value)} /></Field></div></>}
      {step === 4 && <><Heading eyebrow="05 / Review" title="Ready for client presentation." copy="Confirm the scope, validity and value before generating the quotation." /><div className="grid gap-3 rounded-2xl bg-gray-950 p-5 text-white sm:grid-cols-4"><div><small className="uppercase tracking-widest text-gray-500">Client</small><b className="mt-2 block">{data.client_name}</b></div><div><small className="uppercase tracking-widest text-gray-500">Package</small><b className="mt-2 block">{data.package_name}</b></div><div><small className="uppercase tracking-widest text-gray-500">Services</small><b className="mt-2 block">{enabledCount} enabled</b></div><div className="rounded-xl bg-red-600 p-4 sm:-my-1"><small className="uppercase tracking-widest text-red-100">Final value</small><b className="mt-2 block text-xl">{quotationCurrency(amounts.totalAmount)}</b></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Subtotal', amounts.subtotal], ['Discount', -amounts.discount], ['Taxable', amounts.taxableValue], [`GST (${data.gst_percent}%)`, amounts.gstAmount], ['Total', amounts.totalAmount]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-gray-200 p-4"><small className="font-bold uppercase tracking-wider text-gray-400">{label}</small><b className="mt-2 block text-gray-950">{quotationCurrency(Number(value))}</b></div>)}</div><div className="mt-5 flex gap-3 rounded-xl border border-amber-100 bg-amber-50 p-4 text-sm text-amber-900"><CircleAlert size={18} className="shrink-0" /><p>This quotation is valid until <b>{data.valid_until}</b>. It does not reserve the event date until the Baraat Management Contract is signed and booking payment is received.</p></div></>}
    </div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-gray-100 bg-gray-50 px-5 py-4 sm:px-7"><div className="text-[11px] font-semibold text-gray-400">{draftSaved ? 'Draft saved in this browser' : `Step ${step + 1} of ${STEPS.length}`}</div><div className="flex gap-2">{step > 0 && <button type="button" onClick={() => setStep(current => current - 1)} className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-xs font-bold"><ChevronLeft size={14} /> Back</button>}{step < STEPS.length - 1 ? <button type="button" onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-gray-950 px-5 py-2.5 text-xs font-bold text-white">Continue <ChevronRight size={14} /></button> : <button type="button" onClick={submit} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-5 py-2.5 text-xs font-bold text-white disabled:opacity-50"><Save size={14} /> {saving ? 'Saving...' : submitLabel}</button>}</div></div></div>
    {error && <div className="mt-4 flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700"><CircleAlert size={17} /> {error}</div>}
  </div>;
}
