'use client';

import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, ArrowLeft, CalendarClock, CarFront, CheckCircle2, Download, FileText, Loader2, Pencil, Plus, Search, Truck, Upload, Wrench, X } from 'lucide-react';
import CrmHeader from '../components/CrmHeader';
import { useSidebar } from '../sidebar-context';
import { useCrmProfile } from '../lib/useCrmProfile';
import { resolveModuleAccess } from '../../../lib/modulePermissions';
import { resolveSectionAccess } from '../../../lib/crmSectionPermissions';
import {
  ASSET_CATEGORIES, ASSET_STATUSES, DOCUMENT_TYPES, MAINTENANCE_TYPES, addDocument, addMaintenance, createAsset,
  documentState, downloadAssetFile, loadAssetDashboard, loadAssetDetails, maintenanceState, openAssetFile, updateAsset,
  type Asset, type AssetDocument, type AssetInput, type Maintenance,
} from './asset-data';

type Portal='crm'|'workspace';
type Detail={maintenance:Maintenance[];documents:AssetDocument[]};
const money=(value:number|null)=>value==null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
const date=(value:string|null)=>value?new Date(`${value}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—';
const statusStyle:Record<string,string>={'Available':'bg-emerald-50 text-emerald-700','Under Maintenance':'bg-amber-50 text-amber-700','Inactive':'bg-gray-100 text-gray-600'};

export default function AssetManagementView({portal}:{portal:Portal}){
  const{open}=useSidebar();const{profile,loading:profileLoading}=useCrmProfile();const[assets,setAssets]=useState<Asset[]>([]);const[documentIndex,setDocumentIndex]=useState<Array<{asset_id:string;expiry_date:string|null}>>([]);const[maintenanceIndex,setMaintenanceIndex]=useState<Array<{asset_id:string;next_maintenance_date:string|null}>>([]);const[selectedId,setSelectedId]=useState('');const[detail,setDetail]=useState<Detail>({maintenance:[],documents:[]});const[tab,setTab]=useState<'overview'|'maintenance'|'documents'>('overview');const[search,setSearch]=useState('');const[category,setCategory]=useState('');const[status,setStatus]=useState('');const[loading,setLoading]=useState(true);const[detailLoading,setDetailLoading]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[modal,setModal]=useState<'asset'|'maintenance'|'document'|null>(null);const[editing,setEditing]=useState<Asset|null>(null);
  const allowed=portal==='crm'?resolveSectionAccess(profile?.role,profile?.sectionAccess,'assetManagement'):resolveModuleAccess(profile?.role,profile?.moduleAccess,'assetManagement');
  const selected=assets.find(asset=>asset.id===selectedId)||null;
  const refresh=useCallback(async(preferred?:string)=>{setLoading(true);setError('');try{const data=await loadAssetDashboard();setAssets(data.assets);setDocumentIndex(data.documents);setMaintenanceIndex(data.maintenance);setSelectedId(current=>preferred||(data.assets.some(a=>a.id===current)?current:(data.assets[0]?.id||'')));}catch(cause){setError(cause instanceof Error?cause.message:'Unable to load assets.')}finally{setLoading(false)}},[]);
  const refreshDetail=useCallback(async(id:string)=>{setDetailLoading(true);try{setDetail(await loadAssetDetails(id))}catch(cause){setError(cause instanceof Error?cause.message:'Unable to load asset details.')}finally{setDetailLoading(false)}},[]);
  useEffect(()=>{if(allowed)refresh()},[allowed,refresh]);useEffect(()=>{if(selectedId)refreshDetail(selectedId);else setDetail({maintenance:[],documents:[]})},[selectedId,refreshDetail]);
  const visible=useMemo(()=>assets.filter(a=>(!category||a.category===category)&&(!status||a.status===status)&&(!search||`${a.asset_name} ${a.registration_number}`.toLowerCase().includes(search.toLowerCase()))),[assets,search,category,status]);
  const alertAssets=new Set(documentIndex.filter(d=>['Expired','Expiring Soon'].includes(documentState(d.expiry_date).label)).map(d=>d.asset_id));
  const reminders=maintenanceIndex.map(row=>({row,state:maintenanceState(row.next_maintenance_date)})).filter(item=>item.state);
  const stats=[['Total Assets',assets.length,Truck],['Available',assets.filter(a=>a.status==='Available').length,CheckCircle2],['Under Maintenance',assets.filter(a=>a.status==='Under Maintenance').length,Wrench],['Document Alerts',alertAssets.size,AlertTriangle]] as const;
  function done(message:string){setNotice(message);window.setTimeout(()=>setNotice(''),3000)}
  if(profileLoading)return <Centered label="Checking access…"/>;
  if(!allowed)return <><CrmHeader title="Asset Management" subtitle="Company vehicles, maintenance and documents" onMenuClick={open}/><div className="m-4 rounded-2xl border border-red-200 bg-red-50 p-5 text-sm font-semibold text-red-700 sm:m-6">You do not have permission to access Asset Management.</div></>;
  return <><CrmHeader title="Asset Management" subtitle="Company vehicles, maintenance and documents" onMenuClick={open}/><main className="space-y-4 p-4 sm:p-6">
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{stats.map(([label,value,Icon])=><div key={label} className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-[9px] font-black uppercase tracking-widest text-gray-400">{label}</span><Icon size={16} className="text-red-600"/></div><b className="mt-3 block text-2xl text-gray-950">{value}</b></div>)}</div>
    {reminders.length>0&&<div className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3"><CalendarClock size={17} className="mt-0.5 shrink-0 text-amber-700"/><div><b className="text-sm text-amber-900">{reminders.length} maintenance reminder{reminders.length===1?'':'s'}</b><p className="mt-0.5 text-xs text-amber-700">Upcoming, due or overdue maintenance needs attention.</p></div></div>}
    {error&&<Feedback tone="error">{error}</Feedback>}{notice&&<Feedback tone="success">{notice}</Feedback>}
    <div className="grid gap-3 rounded-2xl border border-gray-200 bg-white p-3 shadow-sm md:grid-cols-[minmax(220px,1fr)_180px_180px_auto]"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or registration" className="w-full rounded-xl border border-gray-200 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-red-400"/></label><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-gray-200 px-3 py-2.5 text-sm"><option value="">All categories</option>{ASSET_CATEGORIES.map(v=><option key={v}>{v}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-gray-200 px-3 py-2.5 text-sm"><option value="">All statuses</option>{ASSET_STATUSES.map(v=><option key={v}>{v}</option>)}</select><button onClick={()=>{setEditing(null);setModal('asset')}} className="inline-flex items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 text-xs font-bold text-white"><Plus size={16}/>Add Asset</button></div>
    <div className="grid min-h-[580px] overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm lg:grid-cols-[340px_minmax(0,1fr)]">
      <section className={`${selected?'hidden lg:block':''} border-r border-gray-200`}><div className="border-b px-4 py-3"><b className="text-sm">Assets</b><span className="ml-2 text-xs text-gray-400">{visible.length}</span></div><div className="max-h-[680px] divide-y overflow-y-auto">{loading?<Centered label="Loading assets…"/>:visible.length?visible.map(asset=><button key={asset.id} onClick={()=>{setSelectedId(asset.id);setTab('overview')}} className={`w-full p-4 text-left transition ${selectedId===asset.id?'bg-red-50/70':'hover:bg-gray-50'}`}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><b className="block truncate text-sm">{asset.asset_name}</b><p className="mt-1 truncate text-xs font-semibold text-gray-500">{asset.registration_number}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[8px] font-black uppercase ${statusStyle[asset.status]}`}>{asset.status}</span></div><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-gray-400">{asset.category}</p></button>):<Empty title="No assets found" text="Add an asset or change the current filters."/>}</div></section>
      <section className={`${!selected?'hidden lg:flex':''} min-w-0 flex-col`}>{selected?<><div className="border-b p-4 sm:p-5"><button onClick={()=>setSelectedId('')} className="mb-3 inline-flex items-center gap-1 text-xs font-bold text-gray-500 lg:hidden"><ArrowLeft size={14}/>Back to assets</button><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-xl font-black">{selected.asset_name}</h2><p className="mt-1 text-sm text-gray-500">{selected.registration_number} · {selected.category}</p><span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${statusStyle[selected.status]}`}>{selected.status}</span></div><div className="flex flex-wrap gap-2"><button onClick={()=>{setEditing(selected);setModal('asset')}} className="inline-flex items-center gap-2 rounded-xl border border-gray-200 px-3 py-2 text-xs font-bold"><Pencil size={14}/>Edit Asset</button><button onClick={()=>setModal('maintenance')} className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-3 py-2 text-xs font-bold text-white"><Wrench size={14}/>Add Maintenance</button></div></div></div>
      <div className="flex gap-1 overflow-x-auto border-b px-4 pt-2 sm:px-5">{(['overview','maintenance','documents'] as const).map(value=><button key={value} onClick={()=>setTab(value)} className={`whitespace-nowrap border-b-2 px-3 py-3 text-xs font-black uppercase tracking-wider ${tab===value?'border-red-600 text-red-600':'border-transparent text-gray-400'}`}>{value}</button>)}</div>
      <div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-5">{detailLoading?<Centered label="Loading details…"/>:tab==='overview'?<Overview asset={selected} reminder={latestReminder(detail.maintenance)}/>:tab==='maintenance'?<MaintenanceTab rows={detail.maintenance} openFile={path=>openAssetFile(path).catch(e=>setError(e.message))} downloadFile={(path,name)=>downloadAssetFile(path,name).catch(e=>setError(e.message))} add={()=>setModal('maintenance')}/>:<DocumentsTab rows={detail.documents} openFile={path=>openAssetFile(path).catch(e=>setError(e.message))} downloadFile={(path,name)=>downloadAssetFile(path,name).catch(e=>setError(e.message))} add={()=>setModal('document')}/>}</div></>:<Empty title="Select an asset" text="Choose an asset from the list to view its profile."/>}</section>
    </div>
  </main>{modal==='asset'&&<AssetModal initial={editing} close={()=>setModal(null)} saved={async asset=>{setModal(null);await refresh(asset.id);done(editing?'Asset updated successfully.':'Asset added successfully.')}}/>}{modal==='maintenance'&&selected&&<MaintenanceModal asset={selected} close={()=>setModal(null)} saved={async()=>{setModal(null);await Promise.all([refresh(selected.id),refreshDetail(selected.id)]);done('Maintenance added successfully.')}}/>}{modal==='document'&&selected&&<DocumentModal asset={selected} close={()=>setModal(null)} saved={async()=>{setModal(null);await Promise.all([refresh(selected.id),refreshDetail(selected.id)]);done('Document uploaded successfully.')}}/>}</>;
}

function latestReminder(rows:Maintenance[]){return rows.map(r=>({row:r,state:maintenanceState(r.next_maintenance_date)})).filter(v=>v.state).sort((a,b)=>(a.row.next_maintenance_date||'').localeCompare(b.row.next_maintenance_date||''))[0]||null}
function Overview({asset,reminder}:{asset:Asset;reminder:ReturnType<typeof latestReminder>}){const fields=[['Asset Name',asset.asset_name],['Category',asset.category],['Registration Number',asset.registration_number],['Brand',asset.brand||'—'],['Model',asset.model||'—'],['Manufacturing Year',asset.manufacturing_year||'—'],['Color',asset.color||'—'],['Purchase Date',date(asset.purchase_date)],['Purchase Cost',money(asset.purchase_cost)],['Odometer',asset.odometer_reading==null?'—':`${asset.odometer_reading.toLocaleString('en-IN')} km`],['Status',asset.status]];return <div>{reminder?.state&&<div className={`mb-5 rounded-xl border px-4 py-3 text-sm font-bold ${reminder.state.className}`}>Next maintenance: {date(reminder.row.next_maintenance_date)} · {reminder.state.label}</div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{fields.map(([label,value])=><div key={label} className="rounded-xl bg-gray-50 p-3"><span className="text-[9px] font-black uppercase tracking-widest text-gray-400">{label}</span><p className="mt-1 text-sm font-bold text-gray-800">{value}</p></div>)}</div></div>}
function MaintenanceTab({rows,openFile,downloadFile,add}:{rows:Maintenance[];openFile:(path:string)=>void;downloadFile:(path:string,name:string)=>void;add:()=>void}){return <div><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-black">Maintenance History</h3><button onClick={add} className="inline-flex items-center gap-1 text-xs font-bold text-red-600"><Plus size={14}/>Add</button></div>{rows.length?<div className="space-y-3">{rows.map(row=><article key={row.id} className="rounded-2xl border border-gray-200 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><b className="text-sm">{row.maintenance_type}</b><p className="mt-1 text-xs text-gray-400">{date(row.maintenance_date)} · Added by {row.creator_name}</p></div><b className="text-sm text-red-600">{money(row.total_cost)}</b></div><dl className="mt-4 grid gap-3 text-xs sm:grid-cols-2"><Info label="Work Done" value={row.description}/><Info label="Changed / Replaced" value={row.items_changed||'—'}/><Info label="Next Maintenance" value={date(row.next_maintenance_date)}/><Info label="Notes" value={row.notes||'—'}/></dl>{row.bill_path&&<div className="mt-4 flex flex-wrap gap-4"><button onClick={()=>openFile(row.bill_path!)} className="inline-flex items-center gap-2 text-xs font-bold text-red-600"><FileText size={14}/>View Bill</button><button onClick={()=>downloadFile(row.bill_path!,row.bill_name||'maintenance-bill')} className="inline-flex items-center gap-2 text-xs font-bold text-gray-700"><Download size={14}/>Download Bill</button></div>}</article>)}</div>:<Empty title="No maintenance history" text="New maintenance entries will appear here and remain preserved."/>}</div>}
function DocumentsTab({rows,openFile,downloadFile,add}:{rows:AssetDocument[];openFile:(path:string)=>void;downloadFile:(path:string,name:string)=>void;add:()=>void}){return <div><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-black">Asset Documents</h3><button onClick={add} className="inline-flex items-center gap-1 text-xs font-bold text-red-600"><Plus size={14}/>Upload</button></div>{rows.length?<div className="grid gap-3 xl:grid-cols-2">{rows.map(row=>{const state=documentState(row.expiry_date);return <article key={row.id} className="rounded-2xl border border-gray-200 p-4"><div className="flex justify-between gap-2"><div><b className="text-sm">{row.document_type}</b><p className="mt-1 text-xs text-gray-400">{row.document_number||'No document number'}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[8px] font-black uppercase ${state.className}`}>{state.label}</span></div><p className="mt-3 text-xs text-gray-500">Issued: {date(row.issue_date)} · Expires: {date(row.expiry_date)}</p><p className="mt-1 text-[10px] text-gray-400">Uploaded by {row.creator_name}</p><div className="mt-3 flex flex-wrap gap-4"><button onClick={()=>openFile(row.file_path)} className="inline-flex items-center gap-2 text-xs font-bold text-red-600"><FileText size={14}/>View</button><button onClick={()=>downloadFile(row.file_path,row.file_name)} className="inline-flex items-center gap-2 text-xs font-bold text-gray-700"><Download size={14}/>Download</button></div></article>})}</div>:<Empty title="No documents uploaded" text="Upload RC, insurance, PUC and other asset documents here."/>}</div>}

function AssetModal({initial,close,saved}:{initial:Asset|null;close:()=>void;saved:(asset:Asset)=>Promise<void>}){const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);const year=Number(f.get('manufacturing_year'))||null,cost=f.get('purchase_cost')?Number(f.get('purchase_cost')):null,odo=f.get('odometer_reading')?Number(f.get('odometer_reading')):null;const input:AssetInput={asset_name:String(f.get('asset_name')),category:String(f.get('category')) as AssetInput['category'],registration_number:String(f.get('registration_number')),brand:String(f.get('brand')),model:String(f.get('model')),manufacturing_year:year,color:String(f.get('color')),purchase_date:String(f.get('purchase_date')),purchase_cost:cost,odometer_reading:odo,status:String(f.get('status')) as AssetInput['status']};try{const asset=initial?await updateAsset(initial.id,input):await createAsset(input);await saved(asset)}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save asset.');setBusy(false)}}return <Modal title={initial?'Edit Asset':'Add Asset'} close={close}><form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="Asset Name *"><input name="asset_name" defaultValue={initial?.asset_name} minLength={2} required/></Field><Field label="Category *"><select name="category" defaultValue={initial?.category||ASSET_CATEGORIES[0]}>{ASSET_CATEGORIES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Registration Number *"><input name="registration_number" defaultValue={initial?.registration_number} required/></Field><Field label="Status *"><select name="status" defaultValue={initial?.status||'Available'}>{ASSET_STATUSES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Brand"><input name="brand" defaultValue={initial?.brand||''}/></Field><Field label="Model"><input name="model" defaultValue={initial?.model||''}/></Field><Field label="Manufacturing Year"><input name="manufacturing_year" type="number" min="1900" max="2200" defaultValue={initial?.manufacturing_year||''}/></Field><Field label="Color"><input name="color" defaultValue={initial?.color||''}/></Field><Field label="Purchase Date"><input name="purchase_date" type="date" defaultValue={initial?.purchase_date||''}/></Field><Field label="Purchase Cost"><input name="purchase_cost" type="number" min="0" step="0.01" defaultValue={initial?.purchase_cost??''}/></Field><Field label="Current Odometer (km)" wide><input name="odometer_reading" type="number" min="0" step="0.1" defaultValue={initial?.odometer_reading??''}/></Field></div><FormEnd busy={busy} error={error} label={initial?'Save Changes':'Add Asset'}/></form></Modal>}
function MaintenanceModal({asset,close,saved}:{asset:Asset;close:()=>void;saved:()=>Promise<void>}){const[busy,setBusy]=useState(false);const[error,setError]=useState('');const key=useRef(crypto.randomUUID());async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget),file=(f.get('bill') as File);try{await addMaintenance(asset.id,{maintenance_date:String(f.get('maintenance_date')),maintenance_type:String(f.get('maintenance_type')),description:String(f.get('description')),items_changed:String(f.get('items_changed')),total_cost:Number(f.get('total_cost')||0),next_maintenance_date:String(f.get('next_maintenance_date')),notes:String(f.get('notes'))},file?.size?file:null,key.current);await saved()}catch(cause){setError(cause instanceof Error?cause.message:'Unable to add maintenance.');setBusy(false)}}return <Modal title="Add Maintenance" subtitle={asset.asset_name} close={close}><form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="Maintenance Date *"><input name="maintenance_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field><Field label="Maintenance Type *"><select name="maintenance_type">{MAINTENANCE_TYPES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Description of Work *" wide><textarea name="description" rows={3} minLength={2} required/></Field><Field label="Changed / Replaced" wide><textarea name="items_changed" rows={2}/></Field><Field label="Total Cost *"><input name="total_cost" type="number" min="0" step="0.01" required/></Field><Field label="Next Maintenance Date"><input name="next_maintenance_date" type="date"/></Field><Field label="Bill / Invoice" wide><input name="bill" type="file" accept="application/pdf,image/jpeg,image/png,image/webp"/></Field><Field label="Additional Notes" wide><textarea name="notes" rows={2}/></Field></div><FormEnd busy={busy} error={error} label="Add Maintenance"/></form></Modal>}
function DocumentModal({asset,close,saved}:{asset:Asset;close:()=>void;saved:()=>Promise<void>}){const[busy,setBusy]=useState(false);const[error,setError]=useState('');const key=useRef(crypto.randomUUID());async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget),file=f.get('file') as File,issue=String(f.get('issue_date')),expiry=String(f.get('expiry_date'));if(issue&&expiry&&expiry<issue){setError('Expiry date cannot be before issue date.');setBusy(false);return}try{await addDocument(asset.id,{document_type:String(f.get('document_type')),document_number:String(f.get('document_number')),issue_date:issue,expiry_date:expiry,notes:String(f.get('notes'))},file,key.current);await saved()}catch(cause){setError(cause instanceof Error?cause.message:'Unable to upload document.');setBusy(false)}}return <Modal title="Upload Document" subtitle={asset.asset_name} close={close}><form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="Document Type *"><select name="document_type">{DOCUMENT_TYPES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Document Number"><input name="document_number"/></Field><Field label="Issue Date"><input name="issue_date" type="date"/></Field><Field label="Expiry Date"><input name="expiry_date" type="date"/></Field><Field label="Document File *" wide><input name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" required/></Field><Field label="Notes" wide><textarea name="notes" rows={2}/></Field></div><FormEnd busy={busy} error={error} label="Upload Document" icon={<Upload size={15}/>}/></form></Modal>}

function Modal({title,subtitle,close,children}:{title:string;subtitle?:string;close:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-gray-950/60 sm:items-center sm:p-4" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:rounded-3xl sm:p-6"><div className="mb-5 flex justify-between"><div><h2 className="text-lg font-black">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-gray-400">{subtitle}</p>}</div><button onClick={close} className="rounded-xl bg-gray-100 p-2"><X size={17}/></button></div>{children}</div></div>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:ReactNode}){return <label className={`agreement-field ${wide?'sm:col-span-2':''}`}><span>{label}</span>{children}</label>}
function FormEnd({busy,error,label,icon}:{busy:boolean;error:string;label:string;icon?:ReactNode}){return <>{error&&<Feedback tone="error">{error}</Feedback>}<button disabled={busy} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{busy?<Loader2 className="animate-spin" size={16}/>:icon}{busy?'Saving…':label}</button></>}
function Feedback({tone,children}:{tone:'error'|'success';children:ReactNode}){return <div className={`mt-3 rounded-xl border px-4 py-3 text-sm font-semibold ${tone==='error'?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{children}</div>}
function Centered({label}:{label:string}){return <div className="flex min-h-40 items-center justify-center gap-2 text-sm text-gray-400"><Loader2 className="animate-spin" size={18}/>{label}</div>}
function Empty({title,text}:{title:string;text:string}){return <div className="flex min-h-52 flex-col items-center justify-center p-8 text-center"><CarFront size={28} className="text-gray-300"/><b className="mt-3 text-sm">{title}</b><p className="mt-1 max-w-xs text-xs leading-5 text-gray-400">{text}</p></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-[9px] font-black uppercase tracking-widest text-gray-400">{label}</dt><dd className="mt-1 whitespace-pre-wrap leading-5 text-gray-700">{value}</dd></div>}
