'use client';
import { useEffect, useState } from 'react';
import { Building2, Check, Save, Shield, User } from 'lucide-react';
import CrmHeader from '../components/CrmHeader';
import { useSidebar } from '../sidebar-context';
import type { BusinessProfile } from '../lib/types';
import { DEFAULT_BUSINESS_PROFILE, getBusinessProfile, saveBusinessProfile } from '../invoices/invoice-config';
import { useCrmProfile } from '../lib/useCrmProfile';

export default function SettingsPage(){
 const {open}=useSidebar(); const [saved,setSaved]=useState(false); const [profile,setProfile]=useState<BusinessProfile>(DEFAULT_BUSINESS_PROFILE);
 const { profile: account } = useCrmProfile();
 useEffect(()=>setProfile(getBusinessProfile()),[]);
 const set=(key:keyof BusinessProfile,value:string)=>setProfile(p=>({...p,[key]:value}));
 const submit=(e:React.FormEvent)=>{e.preventDefault();saveBusinessProfile(profile);setSaved(true);window.setTimeout(()=>setSaved(false),2500)};
 return <><CrmHeader title="Settings" subtitle="Manage your CRM profile, billing identity and invoice payment details" onMenuClick={open}/><form onSubmit={submit} className="mx-auto max-w-5xl space-y-5 p-4 sm:p-6">
  <section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><Heading icon={User} title="Account settings"/><div className="grid gap-5 p-5 sm:grid-cols-3 sm:p-6"><Field label="Full name"><input value={account?.name || ''} readOnly className="bg-gray-50 text-gray-500"/></Field><Field label="Account email"><input value={account?.email || ''} readOnly className="bg-gray-50 text-gray-500"/></Field><Field label="Role"><input value={account?.roleLabel || ''} readOnly className="bg-gray-50 text-gray-500"/></Field></div></section>
  <section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><Heading icon={Building2} title="Business & GST identity"/><div className="grid gap-5 p-5 sm:grid-cols-2 lg:grid-cols-4 sm:p-6"><Field label="Legal business name"><input value={profile.legal_name} onChange={e=>set('legal_name',e.target.value)}/></Field><Field label="Trade name"><input value={profile.trade_name} onChange={e=>set('trade_name',e.target.value)}/></Field><Field label="GSTIN"><input value={profile.gstin} onChange={e=>set('gstin',e.target.value.toUpperCase())} placeholder="Enter registered GSTIN"/></Field><Field label="PAN"><input value={profile.pan} onChange={e=>set('pan',e.target.value.toUpperCase())}/></Field><label className="agreement-field sm:col-span-2 lg:col-span-4"><span>Registered address</span><input value={profile.address} onChange={e=>set('address',e.target.value)}/></label><Field label="City"><input value={profile.city} onChange={e=>set('city',e.target.value)}/></Field><Field label="State"><input value={profile.state} onChange={e=>set('state',e.target.value)}/></Field><Field label="State code"><input value={profile.state_code} onChange={e=>set('state_code',e.target.value)}/></Field><Field label="Pincode"><input value={profile.pincode} onChange={e=>set('pincode',e.target.value)}/></Field><Field label="Billing email"><input type="email" value={profile.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Billing mobile"><input value={profile.mobile} onChange={e=>set('mobile',e.target.value)}/></Field><Field label="Default service SAC"><input value={profile.default_sac_code} onChange={e=>set('default_sac_code',e.target.value)}/></Field><Field label="Authorized signatory"><input value={profile.authorized_signatory} onChange={e=>set('authorized_signatory',e.target.value)}/></Field></div></section>
  <section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><Heading icon={Shield} title="Invoice payment details"/><div className="grid gap-5 p-5 sm:grid-cols-2 lg:grid-cols-3 sm:p-6"><Field label="Bank name"><input value={profile.bank_name} onChange={e=>set('bank_name',e.target.value)}/></Field><Field label="Account name"><input value={profile.account_name} onChange={e=>set('account_name',e.target.value)}/></Field><Field label="Account number"><input value={profile.account_number} onChange={e=>set('account_number',e.target.value)}/></Field><Field label="IFSC"><input value={profile.ifsc} onChange={e=>set('ifsc',e.target.value.toUpperCase())}/></Field><Field label="UPI ID"><input value={profile.upi_id} onChange={e=>set('upi_id',e.target.value)}/></Field></div></section>
  <div className="sticky bottom-20 flex justify-end lg:bottom-4"><button type="submit" className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-6 py-3 text-sm font-bold text-white shadow-lg shadow-red-200 hover:bg-red-700">{saved?<Check size={16}/>:<Save size={16}/>} {saved?'Billing settings saved':'Save settings'}</button></div>
 </form></>;
}
function Heading({icon:Icon,title}:{icon:typeof User;title:string}){return <div className="flex items-center gap-3 border-b border-gray-100 bg-gray-50/60 px-5 py-4"><Icon size={18} className="text-red-600"/><h2 className="text-sm font-extrabold text-gray-900">{title}</h2></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="agreement-field"><span>{label}</span>{children}</label>}