'use client';
import { useEffect, useState } from 'react';
import { BellRing, Building2, Check, Clock3, MessageCircle, Save, Shield, User } from 'lucide-react';
import CrmHeader from '../components/CrmHeader';
import { useSidebar } from '../sidebar-context';
import type { BusinessProfile } from '../lib/types';
import { DEFAULT_BUSINESS_PROFILE, getBusinessProfile, saveBusinessProfile } from '../invoices/invoice-config';
import { useCrmProfile } from '../lib/useCrmProfile';
import { DEFAULT_ATTENDANCE_SETTINGS, getAttendanceSettings, saveAttendanceSettings, type AttendanceSettings } from '../lib/attendance-policy';

export default function SettingsPage(){
 const {open}=useSidebar(); const [saved,setSaved]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [profile,setProfile]=useState<BusinessProfile>(DEFAULT_BUSINESS_PROFILE); const [attendance,setAttendance]=useState<AttendanceSettings>(DEFAULT_ATTENDANCE_SETTINGS);
 const [dailyReport,setDailyReport]=useState({is_enabled:true,recipient_e164:'918830612287',whatsapp_template_name:'daily_staff_report',whatsapp_template_language:'en',max_attempts:3});
 const [reportIntegration,setReportIntegration]=useState({loaded:false,providerConfigured:false,cronConfigured:false});
 const { profile: account } = useCrmProfile();
 const isOwnerAdmin=account?.role==='admin'||account?.role==='super_admin';
 useEffect(()=>{setProfile(getBusinessProfile());getAttendanceSettings().then(setAttendance).catch(()=>{});},[]);
 useEffect(()=>{if(!isOwnerAdmin)return;fetch('/api/crm/daily-staff-report',{cache:'no-store'}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to load WhatsApp settings.');setDailyReport(payload.settings);setReportIntegration({loaded:true,providerConfigured:payload.providerConfigured===true,cronConfigured:payload.cronConfigured===true});}).catch(cause=>setError(cause instanceof Error?cause.message:'Unable to load WhatsApp settings.'));},[isOwnerAdmin]);
 const set=(key:keyof BusinessProfile,value:string)=>setProfile(p=>({...p,[key]:value}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{saveBusinessProfile(profile);if(isOwnerAdmin){setAttendance(await saveAttendanceSettings(attendance));if(reportIntegration.loaded){const response=await fetch('/api/crm/daily-staff-report',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(dailyReport)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to save WhatsApp settings.');setDailyReport(payload.settings);}}setSaved(true);window.setTimeout(()=>setSaved(false),2500)}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save settings.')}finally{setSaving(false)}};
 return <><CrmHeader title="Settings" subtitle="Manage your CRM profile, billing identity and invoice payment details" onMenuClick={open}/><form onSubmit={submit} className="mx-auto max-w-5xl space-y-5 p-4 sm:p-6">
  <section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><Heading icon={User} title="Account settings"/><div className="grid gap-5 p-5 sm:grid-cols-3 sm:p-6"><Field label="Full name"><input value={account?.name || ''} readOnly className="bg-gray-50 text-gray-500"/></Field><Field label="Account email"><input value={account?.email || ''} readOnly className="bg-gray-50 text-gray-500"/></Field><Field label="Role"><input value={account?.roleLabel || ''} readOnly className="bg-gray-50 text-gray-500"/></Field></div></section>
  {isOwnerAdmin&&<section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><Heading icon={Building2} title="Business & GST identity"/><div className="grid gap-5 p-5 sm:grid-cols-2 lg:grid-cols-4 sm:p-6"><Field label="Legal business name"><input value={profile.legal_name} onChange={e=>set('legal_name',e.target.value)}/></Field><Field label="Trade name"><input value={profile.trade_name} onChange={e=>set('trade_name',e.target.value)}/></Field><Field label="GSTIN"><input value={profile.gstin} onChange={e=>set('gstin',e.target.value.toUpperCase())} placeholder="Enter registered GSTIN"/></Field><Field label="PAN"><input value={profile.pan} onChange={e=>set('pan',e.target.value.toUpperCase())}/></Field><label className="agreement-field sm:col-span-2 lg:col-span-4"><span>Registered address</span><input value={profile.address} onChange={e=>set('address',e.target.value)}/></label><Field label="City"><input value={profile.city} onChange={e=>set('city',e.target.value)}/></Field><Field label="State"><input value={profile.state} onChange={e=>set('state',e.target.value)}/></Field><Field label="State code"><input value={profile.state_code} onChange={e=>set('state_code',e.target.value)}/></Field><Field label="Pincode"><input value={profile.pincode} onChange={e=>set('pincode',e.target.value)}/></Field><Field label="Billing email"><input type="email" value={profile.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Billing mobile"><input value={profile.mobile} onChange={e=>set('mobile',e.target.value)}/></Field><Field label="Default service SAC"><input value={profile.default_sac_code} onChange={e=>set('default_sac_code',e.target.value)}/></Field><Field label="Authorized signatory"><input value={profile.authorized_signatory} onChange={e=>set('authorized_signatory',e.target.value)}/></Field></div></section>}
  {isOwnerAdmin&&<section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><Heading icon={Shield} title="Invoice payment details"/><div className="grid gap-5 p-5 sm:grid-cols-2 lg:grid-cols-3 sm:p-6"><Field label="Bank name"><input value={profile.bank_name} onChange={e=>set('bank_name',e.target.value)}/></Field><Field label="Account name"><input value={profile.account_name} onChange={e=>set('account_name',e.target.value)}/></Field><Field label="Account number"><input value={profile.account_number} onChange={e=>set('account_number',e.target.value)}/></Field><Field label="IFSC"><input value={profile.ifsc} onChange={e=>set('ifsc',e.target.value.toUpperCase())}/></Field><Field label="UPI ID"><input value={profile.upi_id} onChange={e=>set('upi_id',e.target.value)}/></Field></div></section>}
  {(account?.role==='admin'||account?.role==='super_admin')&&<section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><Heading icon={Clock3} title="Attendance & reminder settings"/><div className="grid gap-5 p-5 sm:grid-cols-2 lg:grid-cols-3 sm:p-6"><Field label="Attendance lock time"><input type="time" value={attendance.lock_time.slice(0,5)} onChange={e=>setAttendance(v=>({...v,lock_time:e.target.value}))}/></Field><Field label="Punch-in reminder delay (minutes)"><input type="number" min="0" max="240" value={attendance.punch_in_reminder_minutes} onChange={e=>setAttendance(v=>({...v,punch_in_reminder_minutes:Number(e.target.value)}))}/></Field><Field label="Punch-out reminder delay (minutes)"><input type="number" min="0" max="240" value={attendance.punch_out_reminder_minutes} onChange={e=>setAttendance(v=>({...v,punch_out_reminder_minutes:Number(e.target.value)}))}/></Field><Field label="Final reminder before lock (minutes)"><input type="number" min="5" max="180" value={attendance.final_reminder_minutes} onChange={e=>setAttendance(v=>({...v,final_reminder_minutes:Number(e.target.value)}))}/></Field><Field label="Daily report reminder time"><input type="time" value={attendance.daily_report_reminder_time.slice(0,5)} onChange={e=>setAttendance(v=>({...v,daily_report_reminder_time:e.target.value}))}/></Field><div className="agreement-field"><span>Business timezone</span><div className="flex min-h-11 items-center gap-2 rounded-xl border border-gray-200 bg-gray-50 px-3 text-sm font-semibold text-gray-500"><BellRing size={14}/> Asia/Kolkata</div></div><div className="sm:col-span-2 lg:col-span-3"><p className="text-[10px] font-black uppercase tracking-wide text-gray-500">Working days</p><div className="mt-2 flex flex-wrap gap-2">{[['Mon',1],['Tue',2],['Wed',3],['Thu',4],['Fri',5],['Sat',6],['Sun',7]].map(([label,value])=><button type="button" key={String(value)} onClick={()=>setAttendance(v=>({...v,working_days:v.working_days.includes(Number(value))?v.working_days.filter(day=>day!==Number(value)):[...v.working_days,Number(value)].sort()}))} className={`rounded-xl border px-3 py-2 text-xs font-bold ${attendance.working_days.includes(Number(value))?'border-red-600 bg-red-50 text-red-600':'border-gray-200 text-gray-500'}`}>{label}</button>)}</div></div><p className="sm:col-span-2 lg:col-span-3 text-xs leading-relaxed text-gray-400">Each attendance date stays open until the next calendar day at the lock time. Reminders skip non-working days and approved leave, and each reminder is generated only once.</p></div></section>}
  {isOwnerAdmin&&<section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><Heading icon={MessageCircle} title="Daily Staff WhatsApp report"/><div className="grid gap-5 p-5 sm:grid-cols-2 lg:grid-cols-3 sm:p-6"><label className="flex min-h-11 items-center justify-between gap-3 rounded-xl border border-gray-200 px-3 sm:col-span-2 lg:col-span-3"><span><b className="block text-xs text-gray-900">Automatic daily report</b><small className="text-[10px] text-gray-400">Sends the previous working day after the 05:00 attendance lock</small></span><input type="checkbox" checked={dailyReport.is_enabled} onChange={e=>setDailyReport(v=>({...v,is_enabled:e.target.checked}))} className="h-4 w-4 accent-red-600"/></label><Field label="Boss WhatsApp number"><input inputMode="tel" value={`+${dailyReport.recipient_e164}`} onChange={e=>setDailyReport(v=>({...v,recipient_e164:e.target.value.replace(/\D/g,'')}))} placeholder="+91 8830612287"/></Field><Field label="Approved template name"><input value={dailyReport.whatsapp_template_name} onChange={e=>setDailyReport(v=>({...v,whatsapp_template_name:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,'')}))}/></Field><Field label="Template language"><input value={dailyReport.whatsapp_template_language} onChange={e=>setDailyReport(v=>({...v,whatsapp_template_language:e.target.value.trim()}))} placeholder="en"/></Field><Field label="Maximum attempts"><input type="number" min="1" max="5" value={dailyReport.max_attempts} onChange={e=>setDailyReport(v=>({...v,max_attempts:Number(e.target.value)}))}/></Field><div className="agreement-field"><span>Automatic send time</span><div className="flex min-h-11 items-center rounded-xl border border-gray-200 bg-gray-50 px-3 text-sm font-semibold text-gray-500">05:00 AM · Asia/Kolkata</div></div><div className="agreement-field"><span>Production readiness</span><div className="flex min-h-11 flex-wrap items-center gap-2 rounded-xl border border-gray-200 bg-gray-50 px-3"><StatusDot ok={reportIntegration.providerConfigured} label="WhatsApp API"/><StatusDot ok={reportIntegration.cronConfigured} label="Cron secret"/></div></div><p className="sm:col-span-2 lg:col-span-3 text-xs leading-relaxed text-gray-400">The PDF is stored privately in Supabase and sent through the approved WhatsApp Business template. API credentials are never exposed in this screen or browser code.</p></div></section>}
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
  {isOwnerAdmin&&<div className="sticky bottom-20 flex justify-end lg:bottom-4"><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-6 py-3 text-sm font-bold text-white shadow-lg shadow-red-200 hover:bg-red-700 disabled:opacity-50">{saved?<Check size={16}/>:<Save size={16}/>} {saving?'Saving...':saved?'Settings saved':'Save settings'}</button></div>}
 </form></>;
}
function Heading({icon:Icon,title}:{icon:typeof User;title:string}){return <div className="flex items-center gap-3 border-b border-gray-100 bg-gray-50/60 px-5 py-4"><Icon size={18} className="text-red-600"/><h2 className="text-sm font-extrabold text-gray-900">{title}</h2></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="agreement-field"><span>{label}</span>{children}</label>}
function StatusDot({ok,label}:{ok:boolean;label:string}){return <span className={`inline-flex items-center gap-1.5 rounded-full px-2 py-1 text-[9px] font-black ${ok?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}><i className={`h-1.5 w-1.5 rounded-full ${ok?'bg-emerald-500':'bg-amber-500'}`}/>{label}: {ok?'Ready':'Needs setup'}</span>}
